### ISSUE TITLE
Clarify return value of CL_MEM_HOST_PTR query in case of CL_MEM_ALLOC_HOST_PTR and CL_MEM_COPY_HOST_PTR

### ISSUE THREAD

**Issue by niranjanjoshi121** [KhronosGroup/OpenCL-Docs#1008]
As per  https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_MEM_HOST_PTR, the query should return a valid host pointer for CL_MEM_USE_HOST_PTR and NULL otherwise. 

https://github.com/KhronosGroup/OpenCL-CTS/pull/1850 adds NULL CL_MEM_HOST_PTR
check for all flag combinations except the CL_MEM_USE_HOST_PTR.

However, with this change, the tests failed on some implementations and passed on others, especially due to difference in behaviour for the case of CL_MEM_COPY_HOST_PTR

Should CL_MEM_COPY_HOST_PTR case be returning NULL or something else for CL_MEM_HOST_PTR query?

**Comment by bashbaug** [comment]
I think the spec is correct in this case and the query for `CL_MEM_HOST_PTR` should only return a non-NULL pointer when the memory object was created with `CL_MEM_USE_HOST_PTR`.  In particular, I think that the query for `CL_MEM_HOST_PTR` should return NULL when the memory object was created with `CL_MEM_COPY_HOST_PTR`.  The reason why is because the host pointer passed with `CL_MEM_COPY_HOST_PTR` is only used to initialize the contents of the memory object during creation.  Once the memory object is created and the data has been copied, the host pointer is no longer meaningful, and indeed it may no longer even be valid.

If others in the working group agree then perhaps this (spec) issue can be closed with no action required?
