### ISSUE TITLE
asciidoctor errors due to long table cells

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#1109]
When building the PDF specs asciidoctor emits two errors (currently) because table cells span more than one page:

```
asciidoctor: ERROR: the table cell on page 388 has been truncated; Asciidoctor PDF does not support table cell content that exceeds the height of a single page
asciidoctor: ERROR: the table cell on page 410 has been truncated; Asciidoctor PDF does not support table cell content that exceeds the height of a single page
```

These are the table cells for `CL_COMMAND_BUFFER_FLAGS_KHR` and `CL_MUTABLE_DISPATCH_UPDATABLE_FIELDS_KHR`.

Options to fix these:

1. Adjust the table column widths so these cells fit on one page, by giving more width to the "Description" column.
2. Refactor or otherwise shorten the text so these cells fit on one page.
3. Move some or all of these descriptions outside of the table.

**Comment by oddhack** [comment]
IIRC this is one reason we use lists instead of tables for describing enums in the Vulkan spec. The rows may continue growing over time as more extensions are added, so whatever solution is used should probably be more robust to that than #1. We also ran into that a lot with the OpenGL spec state tables, which kept having to be refactored and refactored in successive versions so each table fit on a single PDF page.
