### ISSUE TITLE
Missing list of operations in the extension specification for cl_khr_subgroups

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#146]
Unless I've missed something, the list of operations supported by the scan and reduction built-in functions added by `cl_khr_subgroups` is not documented in the extension specification.

**Comment by bashbaug** [comment]
I think the rationale would be that the because the `cl_khr_subgroups` scan and reduction functions are added to the "work group functions" table they inherit the same set of operations as the work group scan and reduction functions, but that's confusing on many levels.  I think it would be better to describe these functions in their own table and to list the set of supported ops explicitly.  I'll fix this - I have an item on my TODO list to add some clarifying text regarding `cl_khr_subgroups` and independent forward progress anyhow.

**Comment by bashbaug** [comment]
@kpet, I think we can close this issue now that #148 has been merged?

**Comment by kpet** [comment]
Yup, closing.
