### ISSUE TITLE
Several Minor OpenCL Spec Issues

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#186]
I found a handful of minor spec issues that I would like to address with a single PR.  In no particular order:

The description for [CL_DEVICE_EXTENSIONS](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#CL_DEVICE_EXTENSIONS) describes a list of Khronos extension names that must be supported by all devices supporting OpenCL C 2.0, including `cl_khr_image2d_from_buffer`.  At the very least, I think `cl_khr_image2d_from_buffer` should be removed from this list, since it is an API-only extension (see [related CTS test](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/compiler/test_compiler_defines_for_extensions.cpp#L48)).  Better is to revisit the test and to add any other missing extensions.  Best, IMHO, is to remove the list entirely, see #119.

In [Options Controlling the OpenCL C version](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#opencl-c-version), in the description with the `-cl-std=CL1.2` option describes behavior for devices supporting OpenCL C 1.0, but I think it should also describe behavior for devices supporting OpenCL C 1.1.

The description for the `CL_MAX_SIZE_RESTRICTION_EXCEEDED` error case for [clSetKernelArg](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#clSetKernelArg) explicitly describes the `cl::max_size` attribute from the OpenCL 2.2 C++ Kernel Language, and a `SpvDecorationMaxByteOffset` in SPIR-V.  At the very least, I think this should refer to the **MaxByteOffset** SPIR-V **Decoration** instead, which uses the terms in the [SPIR-V Spec](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_decoration_a_decoration).  I wonder if this language can be loosened though, so it doesn't need to be updated if similar functionality is available through other mechanisms?

Finally, in the [Required Capabilities section for SPIR-V 1.1](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_Env.html#required-capabilities-1.1), **SubgroupDispatch** is called out for OpenCL 2.2 and newer, but I think this should be for OpenCL 2.1 and newer instead.

If there are no objections I will create a single PR to address all of these issues.  Thanks!

**Comment by kpet** [comment]
1. On the `CL_DEVICE_EXTENSIONS` issue, I think we still want to require that the extension string be reported (so that 1.x applications that relied on the extension can run unmodified). We could fix the issue you described by changing the text to say "devices that support OpenCL 2.0".

2. Yes.

3. `CL_MAX_SIZE_RESTRICTION_EXCEEDED`. I think we should remove the reference to `cl::max_size`. Agree we should refer to the **MaxByteOffset** SPIR-V **Decoration**. The description of the error code refers to the 1.2 SPIR-V specification but the feature was introduced in 1.1 and the 1.1 specification has the correct text. Do we want to change the version as well? I think I would need to see a proposed loosening of the language to get a better idea of what you have in mind.

4. On **SubgroupDistpatch**. I strongly disagree with just updating the spec. This would essentially introduce a new feature requirement to OpenCL 2.1 which conformant implementations in the field might not support. I think we should:
* Spec and implement conformance tests
* Make sure we have two passing implementations (which will probably require adding support to the SPIR-V LLVM Translator)
* Agree how we represent the new feature. I think I'd be happy with just making the change as a patch version as this was probably intended to work in 2.1 (as evidenced by the presence of `CL_KERNEL_COMPILE_NUM_SUB_GROUPS`). We can use the extended versioning extension to report these now. Linking https://gitlab.khronos.org/opencl/OpenCL-Docs/merge_requests/120 and https://gitlab.khronos.org/spirv/SPIR-V/issues/525 where this was touched on.

**Comment by kpet** [comment]
Note we already have https://github.com/KhronosGroup/OpenCL-CTS/issues/12 and https://github.com/KhronosGroup/OpenCL-CTS/issues/24 that describe missing conformance tests.

**Comment by bashbaug** [comment]
Interesting - I thought (4) was a simple typo, but yes, it seems like it is quite the can of worms instead.  I'm fine leaving it alone, for now at least.

In the meantime, I'll create a PR for (1), (2), and (3).  Thanks!

**Comment by alycm** [comment]
For (1): I agree that listing `cl_khr_image2d_from_buffer` there seems pretty arbitrary.  If the list remains, however, should `cl_khr_subgroups` be listed for 2.1?

**Comment by bashbaug** [comment]
> If the list remains, however, should `cl_khr_subgroups` be listed for 2.1?

I don't think we can put `cl_khr_subgroups` in the list of extensions that must be supported by all OpenCL 2.1 implementations since `cl_khr_subgroups` requires support for [subgroup independent forward progress](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS).

**Comment by alycm** [comment]
I merged https://github.com/KhronosGroup/OpenCL-Docs/pull/195, which addresses (1)-(3).   I don't think there is an intent to do anything about (4)?

**Comment by bashbaug** [comment]
Yes, I think I can close this issue now, since we are not going to do anything for (4).  Thanks!
