### ISSUE TITLE
Need for clSetContextReleaseCallback?

### ISSUE THREAD

**Issue by Kerilk** [KhronosGroup/OpenCL-Docs#187]
When creating a `cl_context` using either `clCreateContext` or `clCreateContextFromType`, a callback can be given. The function can optionally be given a `user_data` pointer, that will be provided to the callback when it is invoked. The callback can be called several time, and potentially after the user called `clReleaseContext`.

If the `user_data` pointer is dynamically allocated, the user has no way to know when it is safe to free this pointer. A `clSetContextReleaseCallback` could be used to solve this issue. The signature would be similar to `clSetProgramReleaseCallback`.

```c
cl_int clSetContextReleaseCallback(
    cl_context context,
    void (CL_CALLBACK* pfn_notify)(cl_context context, void* user_data),
    void* user_data);
```

**Comment by bashbaug** [comment]
Discussed in the July 7th teleconference and agreed to add this function to OpenCL 3.0.  Assigning to myself to create a PR for review.

**Comment by bashbaug** [comment]
I've created https://github.com/KhronosGroup/OpenCL-Docs/pull/346 to fix this issue.

Note that I chose to name the new function `clSetContextDestructorCallback` instead of `clSetContextReleaseCallback`.  This name matches `clSetMemObjectDestructorCallback` and I believe this name is more accurate than "release" because the callback should be called when the context reference count reaches zero and hence the context is destroyed, not when the context is released.
