### ISSUE TITLE
OpenCL 2.1 changes kernel language constraints for subgroups

### ISSUE THREAD

**Issue by neildhickey** [KhronosGroup/OpenCL-Docs#19]
In OpenCL 2.1, setting the opencl pragma cl_khr_subgroups is no longer required to use subgroup operations as they are now core, however, OpenCL 2.1 still uses the OpenCL 2.0 c kernel language specification which states that you need to set this pragma.

Since we do not have kernel version 2.1 it is not possible to support this changed behaviour.

We can solve this in two ways as I can see

1) Create a CL 2.1 C language spec/ allowing us to have a -cl-std=cl2.1 in clang which handles this difference correctly
2) Relax the requirement to set the pragma in CL2.0 as we did with cl_khr_fp64

I feel supporting an additional spec and implementation for this relatively small difference would be a lot of unnecessary overhead.

**Comment by bashbaug** [comment]
This probably deserves an issue of its own, but it's never been clear to me why an extension that purely adds new functions (like subgroups) requires a pragma.  If we go with (2) and relax the requirement for a pragma for subgroups in OpenCL 2.0, does something break?  Can we relax the requirement for a pragma for other OpenCL extensions in other OpenCL versions as well?

Note: Extensions such as `cl_khr_fp16` and `cl_khr_fp64` are a bit different: They change fundamental compiler behavior, in this case by enabling use of the new types and literals.  So long as they're extensions (true for `cl_khr_fp16` today, and `cl_khr_fp64` pre-OpenCL 1.2), they should require pragmas, since they do not purely add new functions.

**Comment by neildhickey** [comment]
After discussion the decision is not to do either of the above suggestions. The pragma will still have to be used for CL2.1 even though the feature has become core. Closing this issue.
