### ISSUE TITLE
Use of OpenCL API functions from global constructors and desctructors

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#241]
The specification doesn't say anything (that I could find) about the use of OpenCL API functions from global constructors and desctructors. Should we allow it, forbid it or leave it unspecified?

If we allow it, then OpenCL implementations can't use global constructors and desctructors to perform initialisation and cleanup tasks (the execution order of global constructors and destructors is undefined).

If we forbid it, then we have a number of applications to fix (Halide and TVM are two examples that come to mind),

If we keep the status quo, then we have no way of resolving issues similar to https://github.com/kpet/clvk/issues/171.

**Comment by bashbaug** [comment]
In general I don't think this is safe.  A long time ago the OpenCL Intercept Layer used to free OpenCL resources from a global destructor and it failed (crashed) in some cases depending on the order DLLs were unloaded.  I recall similar issues calling into other DLLs that may not have been fully initialized, so I suspect calls from global constructors may have issues also.

The closes equivalent I'm aware of in the OpenCL specs is:

> The behavior of OpenCL APIs called from an interrupt or signal handler is implementation-defined.

I don't think I'd want to expressly forbid using OpenCL APIs from global constructors or destructors, since it's certainly possible to have an implementation where this is valid (imagine a fully statically linked implementation, for example).  I do think a caution about "implementation-defined" behavior  would be wise in this case though.  Perhaps the quoted sentence above should be extended to include global constructors and destructors?

**Comment by alycm** [comment]
I can absolutely understand that middleware layers struggle with this, in particular the destruction part where DLL unload order can cause major issues.  We have hit this in the past with SYCL, but I think that the the current SYCL spec says that programs that would cause this are ill-formed.

The 1.2 OpenCL CTS also used to do this in various places, it looks like some got removed during refactoring though, and none of the instances that I can think of are in the `master` branch.  So historically implementations had to work well enough in these circumstances for those tests to pass.

One historical CTS instance of this:
* https://github.com/KhronosGroup/OpenCL-CTS/blob/d8733efc0f59f6efdcfc0fd558fa4a563bafc343/test_conformance/allocations/main.cpp#L26
* https://github.com/KhronosGroup/OpenCL-CTS/blob/d8733efc0f59f6efdcfc0fd558fa4a563bafc343/test_common/harness/typeWrappers.h#L42

**Comment by kpet** [comment]
@bashbaug That was my thinking as well. Making the behaviour implementation-defined essentially forbids the use of OpenCL API functions in global constructors/destructors to most applications (as applications don't typically target only implementations they know).

@alycm Oh, yes, I remember these. We fixed that as part of our test harness rework series IIRC.

I'll propose a spec PR to say the behaviour is implementation-defined.
