### ISSUE TITLE
Wrong version listed for the introduction of CL_DEPTH

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/OpenCL-Docs#284]
In the current specification, `CL_DEPTH` is marked as “Missing before 1.2” however as far as I can tell, depth images made it into core only in 2.0 and not 1.2.
From the OpenCL API Specification, under “Summary of changes from OpenCL 1.2 to OpenCL 2.0”:

> Images support for 2D image from buffer, depth images and sRGB images.

Looking at the OpenCL Extensions Specification, cl_khr_depth_images is also listed as having been integrated into 2.0, not 1.2.

**Comment by alycm** [comment]
Hello.  Yes, you are correct.  `CL_DEPTH` is listed as being added in 1.2 in `cl.xml`, but it was only an extension then.   The confusion likely came about because it looks iike `CL_DEPTH_KHR` never existed.

At a glance I suspect that `CL_DEPTH_STENCIL` and `CL_UNORM_INT24` are also incorrectly listed in the xml.

**Comment by alycm** [comment]
Sorry this took so long, I've ignored any missing `CL_DEPTH_KHR` etc and just fixed the XML issues that cause the wrong version annotation to appear in the specification: https://github.com/KhronosGroup/OpenCL-Docs/pull/458.
