### ISSUE TITLE
Typo in OpenCL Device Queries table

### ISSUE THREAD

**Issue by fasbjx** [KhronosGroup/OpenCL-Docs#3]
Hi!

In table 3, OpenCL Device Queries, of The OpenCL Specification version v2.2-3
CL_DEIVCE_MAX_ WORK_ITEM_DIMENSIONS has to be read
CL_DEVICE_MAX_ WORK_ITEM_DIMENSIONS

**Comment by bashbaug** [comment]
Thank you for filing this issue - yes, that is definitely a typo!

We're modifying and updating our specification toolchain slightly, so it's likely easiest if we incorporate the fix for this issue into these changes.  Does that work for you?  If so, no action required, otherwise feel free to open a pull request with a fix.

**Comment by bashbaug** [comment]
I believe this issue is now fixed.

https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_API.html#device-queries-table
