### ISSUE TITLE
Add a query to report the last tested version of the CTS

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#304]
The OpenCL WG has agreed on the 2020/05/26 call that OpenCL 3.0 devices will be required to report the last version of the CTS that they have been tested against.

Detailed proposal to come once we've agreed the exact versioning scheme.

**Comment by bashbaug** [comment]
Discussed in the June 30th teleconference.  Decisions were:

* We will add a new query that provides information similar to the Vulkan query for [VkConformanceVersion](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VkConformanceVersion) in spirit, though the exact mechanism will be different due to differences in the way OpenCL and Vulkan version CTS tests.

* The results of the query are expected to be useful to human readers or included in log files.  The ability for machines to parse the results of the query are of secondary importance.

* Therefore we will add a single device query returning a string.  Returning a string simplifies inclusion in log files and can accommodate different ways of expressing the "last tested version of the CTS".

* We considered adding a platform query as well, but decided that a device query is sufficient.
