### ISSUE TITLE
Do OpenCL C feature macros have specified values

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#311]
This was internal issue 226.

Currently feature macros have no specified values, options:

1. Leave it unspecified, implementations may or may not give the macros values.
2. Explicitly specify that they have no value, only their presence is important.
3. Explicitly specify some universal arbitrary value, such as 1.
4. Explicitly specify some value per macro, such as YYYYMM for the date introduced (like C++).
5. Explicitly specify some value per macro, such the version of OpenCL that introduced the feature (following CL_MAKE_VERSION convention)

Discussion on the internal issue leaned towards (5), or (1) or (2).

**Comment by bashbaug** [comment]
The more I think about this, the more I'm leaning towards (1) for now - leave it unspecified.  This matches the defines for extensions, which also are not specified to have a value, or what the value is.

FWIW, Clang appears to define the extension macros to the value `1`.  OpenCL features are trending to follow a similar implementation.  So if feature macros have a defined value, option (3) is the most likely to happen naturally, unless we explicitly choose to go with option (4) or (5) instead.

Here's an example that writes the value of `cl_khr_fp64` to a buffer.  Since we don't specify whether extension defines have a value, I don't think this code is portable:

https://godbolt.org/z/8ebhK3

**Comment by svenvh** [comment]
We might want to consider users who want to leverage the `-Wundef` compiler warning to detect mistyped or accidentally unset defines here.

**Comment by alycm** [comment]
On call 2020-07-21 an alternative to (3) of "any non-zero value" was proposed.   In general there were concerns that option (1) would be incompatible with `#if`.

Outcome of call: create a PR for option (3) as described in the initial comment (i.e. a value of 1).
