### ISSUE TITLE
Values Returned by Properties Array Queries

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#317]
This was internal issue 217.

>> I think you don't strictly need to store the entire list as passed by the application. Nothing clearly calls for the properties to be returned in the same order. You could recompose the list in clGet*Info from internal state.
>> I think we should decide now whether we want the order to ever be significant or the value returned to be the exact list as passed by the user or the implementation's interpretation of that list and make this 100% explicit.

> In addition to the order of queried properties I think we also need to decide what to do for properties that were not specified by the application.  Specifically, is it OK to include default values in the queried properties array?  If so, note that the size of the queried properties array may be larger than the size of the properties array passed by the application.

And a comment in response.

>> Specifically, is it OK to include default values in the queried properties array?

> I would lean toward yes.
> I think these queries are more useful if they return the implementation's interpretation of user-supplied properties and internal defaults. It allows applications (probably more libraries / utilities / tools) to check that the implementation has interpreted the input correctly. This means that we need to make ordering insignificant but I think the opposite would likely result in confusion or dependency issues anyway.

**Comment by bashbaug** [comment]
While this issue is under discussion the amount of testing we can do in CTS tests for the property queries is rather limited.

Let's look at the test for sampler property queries, as an example (https://github.com/KhronosGroup/OpenCL-CTS/pull/858):

This test creates a sampler with the following properties:

```c
    cl_sampler_properties properties[] = {
        CL_SAMPLER_NORMALIZED_COORDS, CL_TRUE,
        CL_SAMPLER_ADDRESSING_MODE, CL_ADDRESS_CLAMP,
        CL_SAMPLER_FILTER_MODE, CL_FILTER_LINEAR,
        0 };
```

Note that the first two properties (`CL_SAMPLER_NORMALIZED_COORDS` and `CL_SAMPLER_ADDRESSING_MODE`) are also the sampler defaults, but the last property (`CL_SAMPLER_FILTER_MODE`) is specifying a non-default property value (the default is `CL_FILTER_NEAREST`).

Specific questions are:

1. Must the queried properties include the first two properties even though they specify defaults?  **Recommendation:** Yes, since they are explicitly passed in, they must be returned by the query.

2. Must the queried properties include the `CL_SAMPLER_FILTER_MODE` property and value since the property value is not a default?  **Recommendation:** Yes, the query is meaningless without this.

3. May the queried properties include other sampler property-value pairs such as the [`cl_khr_mipmap_image`](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_Ext.html#cl_khr_mipmap_image) properties for `CL_SAMPLER_MIP_FILTER_MODE_KHR`?  **Recommendation:** Yes, this is one condition that is needed to allow an implementation to reconstruct an equivalent property array vs. creating a copy of the passed-in properties.

4. May the queried properties return properties in a different order than they were passed in?  **Recommendation:** Yes, this is another condition that is needed to allow an application to reconstruct an equivalent property array vs. creating a copy of the passed-in properties.

For reference, the relevant current spec text for the [`CL_SAMPLER_PROPERTIES`](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#CL_SAMPLER_PROPERTIES) query is:

> If the properties argument specified in clCreateSamplerWithProperties used to create sampler was not NULL, the implementation must return the values specified in the properties argument.

If we adopt the recommendations above, I think we will want to make a few changes for clarity:

> If the properties argument specified in clCreateSamplerWithProperties used to create sampler was not NULL, the implementation must return the properties and values specified in the properties argument.  The implementation may additionally return other default sampler properties and values.  The properties and value pairs may be returned in any order.

**Comment by bashbaug** [comment]
One additional question.  There is an additional condition for:

> If sampler was created using clCreateSampler, or if the properties argument specified in clCreateSamplerWithProperties was NULL, the implementation may return either a param_value_size_ret of 0 (i.e. there are no properties to be returned), or the implementation may return a property value of 0 (where 0 is used to terminate the properties list).

5. If the properties argument specified in clCreateSamplerWithProperties was only a property value of 0 (where 0 is used to terminate the property list), may the query return a param_value_size_ret of 0 (i.e. there are no properties to be returned), or must the query return a valid property list, even if the property list only consists of the 0 terminator?  **Recommendation:** I don't have a strong recommendation for this case.

**Comment by bashbaug** [comment]
We discussed this issue in the August 4th teleconference and decided to go in a slightly different direction:

For the properties queries, we will instead return a copy of the properties passed by the application.  This enables (1) applications to query what they passed when they created the object, and (2) applications or libraries to query a set of properties that can be passed to create a clone of the object.

Based on this resolution, I propose to clarify the description of the sampler properties query and all related properties queries by changing the specification from:

> If the _properties_ argument specified in **clCreateSamplerWithProperties** used to create sampler was not `NULL`, the implementation must return the values specified in the _properties_ argument.

to:

> If the _properties_ argument specified in **clCreateSamplerWithProperties** used to create sampler was not `NULL`, the implementation must return the values specified in the _properties_ argument in the same order and without including additional properties.

Do we still want to keep the additional condition as-is for when the _properties_ argument is `NULL`, or do we instead want to specify that only a _param_value_size_ret_ of zero is valid in this case (i.e. there are no properties to be returned)?
