### ISSUE TITLE
Type inconsistency between cl_mem_properties and cl_pipe_properties

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#323]
`cl_pipe_properties` is typedef'ed to `intptr_t` whose size can vary, `cl_mem_properties` to `cl_bitfield` that has a fixed size. Given that pipes are memory objects, this is a bit confusing and may increase the complexity of some implementations.

Looking around, we seem to have a mix of `intptr_t` and `cl_bitfield` for properties. Is there a good reason for this? Should we change `cl_mem_properties`? What should the policy be going forward?

**Comment by bashbaug** [comment]
Ugh, this is unfortunate.

We have:

```c
// These predate OpenCL 3.0:
typedef intptr_t            cl_context_properties;
typedef cl_bitfield         cl_queue_properties;
typedef intptr_t            cl_pipe_properties;
typedef cl_bitfield         cl_sampler_properties;

// This has "properties" in the name, but is is a specific property and not a property list:
typedef cl_bitfield         cl_command_queue_properties;

// This is the new typedef added for OpenCL 3.0:
typedef cl_bitfield         cl_mem_properties;
```

So, there's no clear precedent whether to use a fixed size "bitfield" for the mem properties, or a variable size "intptr_t".  I think I just used the queue properties assuming they'd be the same.

To be clear, the concern around pipes specifically is that a pipe is a memory object, hence a developer could incorrectly pass an array of mem properties to the create pipe function?  If so, it looks like a C++ compiler will flag this as an error https://godbolt.org/z/9qZBxs, and a C compiler will emit a warning https://godbolt.org/z/rpL8HY - so that's good at least.

I suppose one option we could consider is to define `cl_buffer_properties` and `cl_image_properties` vs. generic `cl_mem_properties`.  I think this would reduce the likelihood of incorrect usage, albeit at the cost of an extra type and inconsistency with the generic `cl_mem_flags`.  I'm hesitant to make too many changes to accommodate pipes given their lack of popularity, but what do you think?

**Comment by kpet** [comment]
>To be clear, the concern around pipes specifically is that a pipe is a memory object, hence a developer could incorrectly pass an array of mem properties to the create pipe function?

Not really. The main immediate concern was that this makes it harder for an implementation to manage properties with common code for all memory objects. The more important discussion though in my opinion is to choose what we want to do going forward and since, as you say, pipes are not a very popular feature, we shouldn't let that specific issue sway the decision too much. 

>I suppose one option we could consider is to define cl_buffer_properties and cl_image_properties vs. generic cl_mem_properties

I'm not sure we'd want that. I can think of several properties that would be common to images and buffers.

**Comment by bashbaug** [comment]
> The more important discussion though in my opinion is to choose what we want to do going forward [...]

Yes, agreed.

I think using the unconditional 64-bit bitfield type is a bit more flexible, since you can always encode a 32-bit or 64-bit pointer into "bitfield" properties, but on 32-bit platforms you cannot put a 64-bit bitfield into "intptr_t" properties.  This is where I'd lean going forward.  I think this makes sense for the buffer and image properties too, since we may want to include bitfield types as part of these properties.

FWIW, in the core spec we require the pipe properties to be `NULL`, and there are no public extensions that have defined pipe properties.  It's possible we could change the pipe properties to a bitfield also, without breaking any shipping code.

**Comment by bashbaug** [comment]
Strawman proposal for discussion:

* Use `cl_bitfield` for `cl_mem_properties`.  For `cl_mem_properties` we will almost certainly want to pass bitfield values equal to or similar to `cl_mem_flags`, which is a bitfield.  This is also consistent with `cl_queue_properties` and `cl_sampler_properties`.

* By default, we should use `cl_bifield` for future properties, unless we have a very good reason to do something differently.

* It's too late to change `cl_context_properties` so we should leave it as-is.

* We should _consider_ changing `cl_pipe_properties` to be a `cl_bitfield` instead of an `intptr_t`, if and only if we can be there are no shipping extensions that define pipe properties.  It's likely that pipe properties would include bitfield properties just like mem properties, and it would like to be consistent, and there are no published core features or extensions that currently use pipe properties, but I suppose there could be shipping extensions that are unpublished that would be affected by this change.

* This change would not currently affect the specifications, but it would affect the headers and XML grammar.

**Comment by bashbaug** [comment]
We discussed this issue in the June 30th teleconference.  Decisions were:

* We will use a 64-bit type for `cl_mem_properties`, consistent with `cl_queue_properties` and `cl_sampler_properties`.

* We will use a 64-bit type for future properties by default, unless we have a very good reason to use a different type instead.

* We will NOT modify `cl_context_properties` or `cl_pipe_properties`, due to concerns about breaking compatibility.  We observed that we _could_ define new APIs that accepted 64-bit properties if necessary, but there is not currently a need to define these APIs.

* The one change we will consider is a new "properties" type or the changing the properties to be a `cl_ulong` instead of a `cl_bitfield`, since this better captures the intent of the properties.  This may affect the headers and the XML grammar, but it will not affect the spec or shipping code, since properties will continue to be a 64-bit type.

@kpet will make a proposal for the new property type.
