### ISSUE TITLE
Common float built-in functions have no precision requirements

### ISSUE THREAD

**Issue by EwanC** [KhronosGroup/OpenCL-Docs#33]
Section 6.12.4 of the 1.2 spec defines common built-in functions that operate on floating point types. However unlike the maths functions from 6.12.2 which have their errors defined as ULPs in section 7.4, there doesn't seem to be a precision requirement for common functions.

The CTS however does check for a certain level of precision. [Degrees](https://github.com/KhronosGroup/OpenCL-CTS/blob/cl22_trunk/test_conformance/commonfns/test_degrees.c#L81) and [radians](https://github.com/KhronosGroup/OpenCL-CTS/blob/cl22_trunk/test_conformance/commonfns/test_radians.c#L81) have a ULP error, while [mix](https://github.com/KhronosGroup/OpenCL-CTS/blob/cl22_trunk/test_conformance/commonfns/test_mix.c#L33
) and [smoothstep](https://github.com/KhronosGroup/OpenCL-CTS/blob/cl22_trunk/test_conformance/commonfns/test_smoothstep.c#L73) look like they use an absolute error.

Should these CTS precision requirements be defined in the spec somewhere? And if so how should the error thresholds be translated for half in the cl_khr_fp16 extension?

**Comment by alycm** [comment]
A collection of notes on this w.r.t. the most recent set of specifications:

As the original report states: the CTS uses a ULP of 2.0 for `degrees` and `radians` for both `float` and `double`.  This could be handled by adding that value to tables 7.1 and 7.3 of the OpenCL C 2.0 language specification, and tables 5 and 6 of the OpenCL 2.2 SPIR-V Environment specification.  Also as the original report states, the CTS isn't a reference for `cl_khr_fp16`, but I will make the arbitrary observation that other builtins with FP32 accuracy of 2 ULP also have FP16 accuracy of 2 ULP.

The CTS using absolute errors for `mix` and `smoothstep` is interesting, because the specifications only use absolute errors for a few operations when unsafe optimizations are enabled.  Default-mode operations always use ULP for errors (so far).

This sentence from the OpenCL C specification:

>The mix and smoothstep functions can be implemented using contractions such as mad or fma.

has implications for embedded profile as there  `mad` has "implementation defined" accuracy.   This probably requires that `mix` and `smoothstep` also have "implementation defined" accuracy in the embedded profile to match.

Finally, other functions from this table, i.e. `max`, `min`, `step` and `sign` are similarly missing ULPs and should probably have 0 ULP.   Technically `clamp` is also missing a ULP value, but it is specified in terms of other functions that already have 0 ULP.

**Comment by EwanC** [comment]
Having a look at the Geometric builtin-ins from 6.12.5 too, I think they might also suffer from the same issue.

Some example geometric ULP requirements from the CTS not documented in spec.

- [Normalize Float](https://github.com/KhronosGroup/OpenCL-CTS/blob/cl22_trunk/test_conformance/geometrics/test_geometrics.cpp#L1055)
- [Normalize Double](https://github.com/KhronosGroup/OpenCL-CTS/blob/cl22_trunk/test_conformance/geometrics/test_geometrics_double.cpp#L919)
- [Length float](https://github.com/KhronosGroup/OpenCL-CTS/blob/cl22_trunk/test_conformance/geometrics/test_geometrics.cpp#L754)
- [Fast Length float](https://github.com/KhronosGroup/OpenCL-CTS/blob/cl22_trunk/test_conformance/geometrics/test_geometrics.cpp#L809)

**Comment by alycm** [comment]
The geometric ULPs in the CTS are directly derived from the formula descriptions in the spec in terms of the existing ULP of the sub-functions.

But certainly those derived values could be listed.
