### ISSUE TITLE
Allow C11 Atomics to Be Used Without Generic Address Space

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#331]
This was internal issue 230.

The legacy OpenCL 1.x atomics only work with named address spaces, the OpenCL 2.x atomics (C11 style) all use generic address space.

In OpenCL 3.0 provisional the C11 style atomics thus got tied to the generic address space feature, but that is undesirable.  It should be possible to support C11 atomic syntax without supporting generic address spaces.

Thus named address spaces should be supported for C11 style atomic functions, specifically the `global` and `local` address spaces.  Overloaded versions of the relevant atomic functions should be added.

**Comment by AnastasiaStulova** [comment]
I think this is related to https://github.com/KhronosGroup/OpenCL-Docs/issues/66

**Comment by alycm** [comment]
So https://github.com/KhronosGroup/OpenCL-Docs/issues/66 is about adding generic address space to legacy atomics, which this issue specifically does not cover.

There was discussion on that point on internal issue 230, the outcome of which favored extending the usability of C11 atomics for the OpenCL C specification.   The legacy atomic point is not "closed" though as it could be handled as a compiler extension when compiling to SPIR-V.

**Comment by bashbaug** [comment]
Discussed in the July 7th teleconference and agreed to add support for the C11 atomic functions with named address spaces, specifically `__global` and `__local`, in addition to the generic address space.  This will allow implementations that do not support the generic address space to use the C11 atomic functions, and could improve performance even for implementations that do support the generic address space.

One specific issue we discussed was the `atomic_compare_exchange` functions, which accept two pointer arguments:

```c
bool atomic_compare_exchange_strong(
    volatile A *object,
    C *expected,
    C desired)
```

For these functions, we agreed that when `object` is a pointer to a named address space, `expected` will be a pointer to the private address space.  In all practical usages `expected` will be a pointer to the private address space, and this avoids needing to add (and test!) all combinations of address spaces for these functions.

I plan to create a PR describing these changes, but I have a few other PRs to create first.  I will assign this issue to me when I start work.  If someone else wants to grab it first, feel free!

**Comment by AnastasiaStulova** [comment]
> For these functions, we agreed that when object is a pointer to a named address space, expected will be a pointer to the private address space. In all practical usages expected will be a pointer to the private address space, and this avoids needing to add (and test!) all combinations of address spaces for these functions.

I don't think pointers in other than private address spaces can be considered to be impractical. They are potentially less frequent in the kernel code but they are used too.

**Comment by bashbaug** [comment]
To be clear, in my [comment above](https://github.com/KhronosGroup/OpenCL-Docs/issues/331#issuecomment-655134295) I am only talking about the `expected` pointer.  In other words, we will support two overloads with named address spaces as follows:

```c
bool atomic_compare_exchange_strong(
    volatile __global A *object, // supported, A can be a pointer to the named __global address space.
    __private C *expected, // supported, C is a pointer to the __private address space.
    C desired)

bool atomic_compare_exchange_strong(
    volatile __local A *object, // also supported, A can be a pointer to the named __local address space.
    __private C *expected, // supported, C is a pointer to the __private address space.
    C desired)
```

But, we will NOT support overloads like these:

```c
bool atomic_compare_exchange_strong(
    volatile __global A *object,
    __global C *expected, // NOT supported, C must point to the __private address space!
    C desired)
```

I think this is by far the most common use-case, but if an application really wants to write to an `expected` pointer in the global or local address space they can still do so, using two steps:

```c
C temp;
atomic_compare_exchange_strong(object, &temp, desired);
*expected = temp;
```

I think this is reasonable and it avoids an explosion of combinations of different named address spaces.

**Comment by AnastasiaStulova** [comment]
I don't disagree that private addr space is generally more common in threads not just for this specific case yet we do support other address spaces too. We have quite many overloads already so why not to provide support for atomics that can avoid extra copies in the case `expected` pointer is in other address spaces. There is no way to avoid the copy otherwise.

**Comment by bashbaug** [comment]
> We have quite many overloads already so why not to provide support for atomics that can avoid extra copies in the case `expected` pointer is in other address spaces. There is no way to avoid the copy otherwise and we don't gain much.

* It's 3x the number of overloads, since we'd need variants for `global`, `local`, and `private` vs. for just `private`.  That's a bunch of extra implementation and testing without clear value (see below).

* The SPIR-V instruction these built-ins will map to is [OpAtomicCompareExchange](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpAtomicCompareExchange).  This instruction returns the "expected" value and doesn't write it to a pointer.  This means that the SPIR-V implementation of these built-ins will require a copy regardless.

* Note that the legacy OpenCL 1.x atomics behaved similarly to the SPIR-V instruction and also returned the "expected" value vs. writing to a pointer.

Honest question: Is there any code in the wild that writes "expected" to the `local` or `global` address space? Is there any hardware that natively supports writing "expected" to anything other to the private address space?

**Comment by AnastasiaStulova** [comment]
> It's 3x the number of overloads, since we'd need variants for global, local, and private vs. for just private.

There are 5 variants of compare exchange so if we add extra address spaces it would make it a dozen or two in total? FYI there are about 17K overloads of BIFs in total in OpenCL right now.

> That's a bunch of extra implementation and testing without clear value (see below).

I also mentioned consistency.

> The SPIR-V instruction these built-ins will map to is OpAtomicCompareExchange. This instruction returns the "expected" value and doesn't write it to a pointer. This means that the SPIR-V implementation of these built-ins will require a copy regardless.

Compiling to SPIR-V is only a secondary flow in OpenCL. The regular compilation is done into a binary. There are also different IR formats than SPIR-V.

> Honest question: Is there any code in the wild that writes "expected" to the local or global address space?

Probably not easy to check.

> Is there any hardware that natively supports writing "expected" to anything other to the private address space?

It is likely to be in a register, depending on how the copy is done. It can probably be optimized out but I am not convinced this is always the case or at least generally the case.

**Comment by alycm** [comment]
> I plan to create a PR describing these changes, but I have a few other PRs to create first. I will assign this issue to me when I start work. If someone else wants to grab it first, feel free!

I'll assign this to me and start adding the agreed changes.  If discussion ends up favoring adding `local` and `global` variants for expected that is purely additive, so it doesn't stop me getting the rest of the builtins added.

**Comment by alycm** [comment]
Call 2020-07-17: For `atomic_compare_exchange_strong` add all the variants, i.e. the cross product of `{global, local}` for `object` and `{global, local, private}` for `expected`.

**Comment by AnastasiaStulova** [comment]
Summary of extra discussions:
1. Should named addr space overloads be available when generic address spaces is supported?
- Implementations are free to provide named AS variants if it executes faster. This is transparent to the user and doesn't force everyone to implement them.
- Some implementation already provide named AS overloads but it was not portable as it was not enforced by the spec.
- One benefit of generic address space is the reduction in binary size. If we force extra overloads explicitly this will not be as easy to achieve.
- Whichever direction is taken it should be consistent across all BIF that have pointers as parameters. 
2. Should atomic pointer be considered in private address space too for completeness?
- This was examined before and rejected.

Conclusion:
- Need more discusion on the topics above.

**Comment by StuartDBrady** [comment]
If we forbid the use of the private address space for pointers passed to atomic functions, this makes it inconsistent as to what is valid when using the generic address space and what is valid without.

I gather that implementations of the atomic functions for private pointers are trivial, in that no two threads may access the same memory through a global pointer, so there is no need for any atomic primitives to be used.

Providing the overloads has the advantage that that is built using macros for all address spaces would not need to do anything special for the private address space. It also avoids complicating the conformance tests by having to explicitly avoid testing for the private address space when the generic address space is not in use.

Another example of how uniformity can be beneficial: SPIR-V allows atomic operations to be performed with the **Function** address space. For an implementation that uses an OpenCL builtin function library, the most straightforward way to implement this is to would be to map to the C11 atomics function using the private address space. If this overload is excluded, then implementations would either have to provide it anyway, or otherwise add extra complexity to their translation, which would complicate testing, as it would not be testable with the OpenCL atomics testing that is already in the CTS.

**Comment by StuartDBrady** [comment]
Note: what I have said goes for _both_ the "object" _and_ the "expected" pointers of functions that have each.

**Comment by alycm** [comment]
I've put this back into "Needs WG discussion" to cover the private pointer point.

**Comment by bashbaug** [comment]
FWIW, OpenCL C does not define the behavior of atomic functions when a generic address space pointer points to the private address space:

> The behavior of atomic operations where pointer arguments to the atomic functions refers to an atomic type in the private address space is undefined.

Same goes for SPIR-V in all OpenCL environments:

> The Pointer operand must be a pointer to the Function, Workgroup, or CrossWorkGroup Storage Classes. Note that an Atomic Instruction on a pointer to the Function Storage Class is valid, but does not have defined behavior.

I think it would be strange and confusing to add atomic function overloads that accept pointers to the named private address space but with undefined behavior.

**Comment by StuartDBrady** [comment]
> FWIW, OpenCL C does not define the behavior of atomic functions when a generic address space pointer points to the private address space.
>
> Same goes for SPIR-V in all OpenCL environments.
> 
> I think it would be strange and confusing to add atomic function overloads that accept pointers to the named private address space but with undefined behavior.

Thanks, @bashbaug. In that case, I agree entirely—my apologies for the noise!

I would prefer that any address space be allowed for the "excepted" pointer—my understanding is we've now agreed upon this.

Given what you've said, I can see no downside to omitting the overload for the "object" pointer: indeed, it even allows the opportunity to catch undefined behavior (which is ideally something that Clang would warn about when using the generic overloads, in cases where address space inference allows it, if it does not already).

**Comment by alycm** [comment]
> Thanks, @bashbaug. In that case, I agree entirely—my apologies for the noise!

Great, I'll move this out of "needs WG discussion".

> I would prefer that any address space be allowed for the "excepted" pointer—my understanding is we've now agreed upon this.

Yes, indeed, https://github.com/KhronosGroup/OpenCL-Docs/issues/363 is under review and does that.
