### ISSUE TITLE
Vector literal l-value restriction

### ISSUE THREAD

**Issue by svenvh** [KhronosGroup/OpenCL-Docs#343]
OpenCL v2.0 s6.1.6 says "A vector literal cannot be used as an l-value.", but Clang currently still accepts `&((int4)(3,2,1,0))`.

A patch to take the restriction into account was proposed [1], but the patch was rejected because it also applied the restriction to braced initializers, which are unaffected by the restriction as they come from C99:

An OpenCL vector literal should be an r-value:
`(int4) (3,2,1,0)`
An elementwise list-initialization of a compound literal vector should continue to be an l-value:
`(int4) {3,2,1,0}`

A further concern was raised in [1] about those syntactically similar constructs having different value category semantics. Clang has been allowing OpenCL vector literals as l-values for almost 10 years, so perhaps we should consider if we want to drop the l-value restriction?

[1] http://lists.llvm.org/pipermail/cfe-dev/2011-September/017267.html

**Comment by keryell** [comment]
I am curious then about the meaning of
```c++
(int4)(3,2,1,0) = (int4)(1,2,3,4);
```
just a no-op?

**Comment by AnastasiaStulova** [comment]
> I am curious then about the meaning of
> 
> ```c++
> (int4)(3,2,1,0) = (int4)(1,2,3,4);
> ```
> 
> just a no-op?

FYI, here is an equivalent example with compound struct literals in C99 https://godbolt.org/z/TK1M6b.

Two temporaries are created and initialized on the stack then the content is copied from one into another. This is of course optimized out and becomes a no-op but from the language perspective, it is not entirely a no-op. I don't know if perhaps some code can be written where it becomes more useful. But clearly, such behavior is C99 conformant.  So it doesn't make sense to forbid one syntax but allow another one. They should both be either allowed or disallowed and if I have to choose I prefer to stay with C behavior wherether possible because it often means that there is a reason for it and that tooling will be provided as we build on top of existing C and C++ compilers.

**Comment by bashbaug** [comment]
Proposal:

Replace the sentence:

> A vector literal cannot be used as an l-value.

With:

> Whether a vector literal can be used as an l-value is implementation-defined.

**Comment by AnastasiaStulova** [comment]
I have just one further suggestion, in order to improve this for OpenCL 3.0 onwards could we say something like:

> Whether a vector literal can be used as an l-value is implementation-defined before OpenCL C 3.0. From OpenCL 3.0 onwards a vector literal can be used as an l-value.

Or is it too late for such a change?

**Comment by bcalidas** [comment]
Qualcomm would prefer the spec language to continue to read "Whether a vector literal can be used as an l-value is implementation-defined."
