### ISSUE TITLE
Clarify support for program global constructors/desctructors in 3.0

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#347]
The functionality is specified as "Missing before 2.2" but the normative section of the specification says nothing about the behaviour in 3.0. Appendix H makes it clear that 3.0 doesn't support the following:
- `CL_PROGRAM_SCOPE_GLOBAL_CTORS_PRESENT`
- `CL_PROGRAM_SCOPE_GLOBAL_DTORS_PRESENT`
- `clSetProgramReleaseCallback`

This should probably be extended to a review of all behaviours described in Appendix H that are not described in the normative sections of the specification.

**Comment by bashbaug** [comment]
To be clear, none of this functionality was removed in OpenCL 3.0, so it's not quite accurate to say that "3.0 doesn't support" the queries or the APIs.  It is fair to say that the the queries and the callback API are not very useful in OpenCL 3.0 though, given that OpenCL 3.0 does not support program scope constructors and destructors.

Do you have a proposal for what you would like to clarify?  If deprecate the queries and the callback API (#348) I think that would improve clarity?

**Comment by alycm** [comment]
Agreed that none of these things are "removed", and the main body descriptions are currently technically correct, but certainly give no indication that only one of the described paths will ever apply to OpenCL 3.0 devices.

Given program scope variables are hard "not supported" in 3.0 rather than "optional", deprecating all three of these would certainly clearly mark them out.  I don't think they need a stronger "removed" wording because they are still present, they're just hard-coded to the "not supported" path as far as the spec is concerned.
