### ISSUE TITLE
Does clEnqueueSVMMigrateMem and clSetProgramSpecializationConstant need to be supported for original CL1.2/2.0/2.1 upgraded to CL3.0?

### ISSUE THREAD

**Issue by nicoljl** [KhronosGroup/OpenCL-Docs#349]
For Shared Virtual Memory part of Appendix H OpenCL 3.0 Backwards Compatibility, as clEnqueueSVMMigrateMem API was instroduced in CL2.1. Is it OK that to support following 2.0 APIs of SVM feature, but not to support clEnqueueSVMMigrateMem API in CL3.0? If this is OK, could related description be added in the spec? 
- clSVMAlloc
- clSVMFree
- clEnqueueSVMFree
- clEnqueueSVMMemcpy
- clEnqueueSVMMemFill
- clEnqueueSVMMap
- clEnqueueSVMUnmap
- clSetKernelArgSVMPointer
- clSetKernelExecInfo

For Intermediate Language Programs part, clSetProgramSpecializationConstant API is introduced in CL2.2. and the other IL related APIs are introduced in CL2.1. Could the IL feature claimed to supported with implementing only the CL2.1 APIs, returning CL_INVALID_PROGRAM for clSetProgramSpecializationConstant API?
- clCreateProgramWithIL

**Comment by bashbaug** [comment]
Hi @nicoljl !

For Khronos folks, we discussed `clEnqueueMigrateMem` as internal issue 245.  In this issue, we concluded that requiring support for `clEnqueueSVMMigrateMem` is reasonable because migrations are only a hint.  This means that a conformant implementation of `clEnqueueSVMMigrateMem` could be implemented more-or-less as an equivalent to a command queue marker, with a bit of extra bookkeeping to track that the command is a migration and not a marker.  Does this make sense, and is this reasonable?

We discussed the optionality of specialization constants in #294 and agreed that `clSetProgramSpecializationConstant` will be required for implementations supporting SPIR-V in OpenCL 3.0.  Note that specialization constants were also required in OpenCL 2.1, in that a SPIR-V module containing **OpSpecConstants** was valid, although without an API to set them they would always use the default value.  Please also be aware of #344 and #345, which may affect the supported specialization constant details, depending how they are resolved.

**Comment by nicoljl** [comment]
Hi, @bashbaug 
Thanks for your reply. But for clEnqueueMigrateMem API, I think it's targeted for discrete GPU devices scenario. I hope it could be 'optional' support for SVM feature when we want to target for host and device share physical memory usage.

**Comment by bashbaug** [comment]
Hi @nicoljl, sorry for the slow reply.  Yes, I agree that `clEnqueueSVMMigrateMem` is most useful for discrete accelerators, but because it doesn't appear to be difficult to provide a uniform API that works for all accelerator types, we are currently requiring it for all devices that support SVM.

Note that OpenCL 1.2 has `clEnqueueMigrateMemObjects` for all device types ([link](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#clEnqueueMigrateMemObjects)).  If you are sharing physical memory between the host and device and hence memory migration is a NOP, I believe that `clEnqeueuSVMMigrateMem` can essentially behave the same as `clEnqueueMigrateMemObjects`, aside from possible input validation and the `CL_EVENT_COMMAND_TYPE`?

**Comment by bashbaug** [comment]
Hello, since we have decided to require `clEnqueueSVMMigrateMem` for OpenCL 3.0 devices that support SVM and have [tests](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/SVM/test_migrate.cpp) for it I think we can close this issue.  Feel free to re-open it if there are still questions - thanks!
