### ISSUE TITLE
Implementing restriction on relaxed memory scope atomic use 

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#354]
The following restriction is hard to implement in tools as it adds extra complexity for specializing one function otherwise we could just disable the relaxed versions of scopes completely that is a straight forward task.

>Using  memory_order_acquire  with  any  built-in  atomic  function  except  atomic_work_item_fencerequires OpenCL C 2.0 or the __opencl_c_atomic_order_acq_rel feature macro.•  Using  memory_order_release  with  any  built-in  atomic  function  except  atomic_work_item_fencerequires OpenCL C 2.0 or the __opencl_c_atomic_order_acq_rel feature macro.•  Using  memory_order_acq_rel  with  any  built-in  atomic  function  except  atomic_work_item_fencerequires OpenCL C 2.0 or the __opencl_c_atomic_order_acq_rel feature macro

Before diving into any suggestion for its alternative ways to specify this it would be good to understand the motivation for special case of this function.

FYI, it was highlighted that there is the following similar restriction in OpenCL 2.0 for this function that has never been implemented in the upstream clang:

> The atomic_work_item_fence(CLK_IMAGE_MEM_FENCE) built-in function can be used to make sure that
> sampler-less   writes   are   visible   to   later   reads   by   the   same   work-item.   Only   a   scope   of memory_scope_work_item  and  an  order  of  memory_order_acq_rel  is  valid  for  atomic_work_item_fencewhen  passed  the  CLK_IMAGE_MEM_FENCE  flag.

**Comment by bashbaug** [comment]
I believe the way we got here was by looking at OpenCL 1.2 device capabilities:

* For the OpenCL 1.2 atomic functions (e.g. `atomic_add`), there is no expectation that they enforce memory consistency, so they are "relaxed" atomics.

* To enforce memory consistency, OpenCL 1.2 has fence functions (e.g. `mem_fence`).  While the definition of these functions is somewhat ambiguous, they appear to describe "acquire-release" fences.

So, in order to describe OpenCL 1.2 device capabilities using the C11 / OpenCL C 2.0 atomic functions, we need to support no more than relaxed memory orders for most atomic functions, but we need to support the acquire and release memory orders for `atomic_work_item_fence`.  This is how we ended up with the wording referenced above and the special case for `atomic_work_item_fence`.

If we want to eliminate the special case and simplify tooling (and maybe the spec also), here are a few options:

1. Eliminate the special case and require that if the acquire-release memory orders are supported for any atomic function then they are supported for all atomic functions, both atomic operations and atomic fences.  This means that an OpenCL 1.2 device moving to OpenCL 3.0 either needs to add support for more than just "relaxed" atomic operations, or will be unable to express OpenCL 1.2 memory fences using the newer `atomic_work_item_fence` function.

2. Only control the availability of the acquire-release memory orders based on the OpenCL C feature macro, but do not try to detect and control how the acquire-release memory orders are used.  If a device supports acquire-release memory orders only for fences and an acquire-release memory order is passed to an atomic operation, then the program is malformed and behavior is undefined.

I thought that option (2) was the intended option but perhaps that isn't the case - ping @alycm to check that the spec is documenting what we intended to document.

For Khronos folks, this was discussed in internal issue 210, and was added by internal merge request 136.

**Comment by alycm** [comment]
I'll definitely admit that this is annoying.  Like Ben said, it was trying to interpret the 1.2 spec, where everything was relaxed order.  But a relaxed order memory fence is a no-op.  Both logically, and explicitly in the OpenCL C 2.0 spec:

> [atomic_work_item_fence] has no effects, if order == memory_order_relaxed

This is also why there are two separate device properties, `CL_​DEVICE_​ATOMIC_​MEMORY_​CAPABILITIES` and `CL_​DEVICE_​ATOMIC_​FENCE_​CAPABILITIES` with different minimum requirements.

> I thought that option (2) was the intended option but perhaps that isn't the case - ping @alycm to check that the spec is documenting what we intended to document.

Yes, it was.  Checking my notes from the meeting 2020-02-06 I wrote "Illegal use of runtime values is UB (exactly as would currently happen if random numbers are passed as flags)".

That's why even though there is a  `__opencl_c_atomic_order_acq_rel` feature macro, the `memory_order_acq_rel` etc. flags are defined as (emphasis mine):

> **Always present** but some uses require support for OpenCL C 2.0 or the __opencl_c_atomic_order_acq_rel feature macro.

But this is exactly what results in the exceptions that this ticket is about.

As for option (1), it would certainly simplify the specification.  It would mean that some devices only supported relaxed order fences, i.e. they would not support any useful fences at all.  I'm not sure how much of a limitation would be for programmers.

**Comment by bashbaug** [comment]
Ah right, this is all sounding familiar again.

To summarize: the way the spec is currently defined, the same memory order enumerations and built-in functions are available regardless whether the `__opencl_c_atomic_order_acq_rel` feature macro is supported or unsupported.  What the `__opencl_c_atomic_order_acq_rel` feature macro does is indicate to applications that the acquire and release memory orders are valid for atomic operations.  Without the `__opencl_c_atomic_order_acq_rel` feature macro, the acquire and release memory orders are only valid for fence operations.

Indeed, the description of `__opencl_c_atomic_order_acq_rel` is:

> The OpenCL C compiler supports enumerations and built-in functions for atomic operations with acquire and release memory consistency orders.

That doesn't seem too bad for tooling.  @AnastasiaStulova , is there a devil in the detail here that I'm missing?

**Comment by AnastasiaStulova** [comment]
> As for option (1), it would certainly simplify the specification. It would mean that some devices only supported relaxed order fences, i.e. they would not support any useful fences at all. I'm not sure how much of a limitation would be for programmers.

There are still `mem_fence,` `read_mem_fence`, `write_mem_fence` that are defined with non-relaxed scope by default.

**Comment by AnastasiaStulova** [comment]
> That doesn't seem too bad for tooling. @AnastasiaStulova , is there a devil in the detail here that I'm missing?

The issue is that excluding the enum completely is relatively easy in tooling but excluding them conditionally on some functions is madness because it needs lots of extra checking in the frontend that not only results in extra complexity in tooling but also increase in parsing time.

> 1. Eliminate the special case and require that if the acquire-release memory orders are supported for any atomic function then they are supported for all atomic functions, both atomic operations and atomic fences. This means that an OpenCL 1.2 device moving to OpenCL 3.0 either needs to add support for more than just "relaxed" atomic operations, or will be unable to express OpenCL 1.2 memory fences using the newer atomic_work_item_fence function.

This sounds good! It feels sensible that if `__opencl_c_atomic_order_acq_rel` is not supported then acquire and release ordering are not available at all, and if  either of those is still needed for the fences then one of the following functions can be used`mem_fence`, `read_mem_fence`, `write_mem_fence`? In addition we could define the default overload of `atomic_work_item_fence` that would use `memory_order_acq_rel` and `memory_scope_work_group`.

`void atomic_work_item_fence(cl_mem_fence_flags flags) // order = emory_order_acq_rel, scope = memory_scope_work_group`

Generally think it is logical that if some implementation doesn't support fully C11/OpenCL 2.0 memory model, they won't be able to have full functionality of OpenCL 2.0 atomics and therefore some limitations will apply.

**Comment by bashbaug** [comment]
Summarizing where we are right now regarding this issue.  I think this is consistent with the discussion in the July 21st teleconference:

If we do nothing, the spec currently says:

* The acquire, release, and acq_rel memory orders are always available and are not protected by any feature macros.
* It is always valid to use the acquire, release, and acq_rel memory orders with `atomic_work_item_fence`, to achieve equivalent functionality to the OpenCL 1.2 `read_mem_fence`, `write_mem_fence`, and `mem_fence` functions.
* It is only sometimes valid to use the acquire, release, and acq_rel memory orders with other atomic functions, such as `atomic_fetch_add`.  The `__opencl_c_atomic_order_acq_rel` feature macro can be used to determine when this usage is valid.  The compiler will NOT provide diagnostics if the acquire, release, or acq_rel memory orders are improperly used with other atomic functions, and this is undefined behavior..
* This is slightly different than the seq_cst memory order, since the seq_cst memory order will be protected by the `__opencl_c_atomic_order_seq_cst` feature macro.  This makes it harder to improperly use the seq_cst memory order, but even if this happens somehow, the compiler will NOT provide diagnostics and this is undefined behavior.

I _think_ this is implementable by tooling and can express all OpenCL 1.2 functionality even if it's a little confusing.

The alternative we are discussing is:

* We protect the acquire, release, and acq_rel memory orders by the `__opencl_c_atomic_order_acq_rel` feature macro, similar to how the seq_cst memory order is protected by the `__opencl_c_atomic_order_seq_cst` feature macro.
* If an implementation chooses to support the `__opencl_c_atomic_order_acq_rel` feature then the acquire, release, and acq_rel memory orders must be supported for all atomic operations.
* As mentioned in a prior comment, this all-or-nothing support either means that all OpenCL 1.2 functionality either cannot be expressed via C11 atomics (specifically for memory fences, if `__opencl_c_atomic_order_acq_rel` is not supported), or that additional functionality is required beyond OpenCL 1.2 (specifically acquire and release atomic operations, if `__opencl_c_atomic_order_acq_rel` is supported).

We need to decide if it's OK to trade off the inability to precisely express OpenCL 1.2 functionality for the increased simplicity.

**Comment by nikhiljnv** [comment]
Does the alternative above break backward compatibility with OpenCL C 1.2? Sounds like it does as memory fences can not be supported.
Also, should any of these approaches will require changes to OpenCL kernels written for OpenCL 1.2 to make them work with OpenCL 3.0?

**Comment by bashbaug** [comment]
Summary of discussion in the July 23rd teleconference:

- The alternative doesn't break backwards compatibility with OpenCL C 1.2 or require changes to OpenCL kernels written for OpenCL 1.2 because the "old" memory fence functions will still be supported: `read_mem_fence`, `write_mem_fence`, and `mem_fence`.  The alternative could mean that the memory fence functions are unable to express via `atomic_work_item_fence` though.

- There wasn't a strong preference for the status quo vs. the alternative.  We agreed to spend a bit more time to consider the tradeoffs more carefully, since this issue does not need to be resolved ASAP.

**Comment by bashbaug** [comment]
Discussed in the August 4th teleconference and decided to keep the spec as-is, so closing this issue without additional action.
