### ISSUE TITLE
OpenCL 3.0 features with OpenCL 2.0 mode

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#359]
In OpenCL 3.0 there are the following statements:

> The   functionality   described   in   the   following   table   requires   support   for   the `opencl_c_subgroups`   feature   macro   and   either   OpenCL   C   2.0   or   the `opencl_c_device_enqueue` feature macro.

(**Note:** `__` are missing from feature macros.)

This seems to imply that `__opencl_c_subgroups`  is available in OpenCL C 2.0? However, we didn't have optional features in OpenCL 2.0 and therefore feature macros weren't available. The closes situation to this could be that `cl_khr_subgroups` is supported in OpenCL 2.0 but then the macro will be `cl_khr_subgroup`... could we clarify this?

**Comment by alycm** [comment]
The missing `__` is likely just an Asciidoctor formatting issue.

Thinking about it for a minute I suspect that the "either OpenCL C 2.0 or" part of that sentence, and others involving subgroups can just be dropped.

**Comment by bashbaug** [comment]
I just created PR #361 which will correct the asciidoctor formatting.

As for the logic in the sentence, I believe it is correct.  Two conditions are needed to use the functionality in the table:

1. Subgroups must be supported.  The only core OpenCL C way to identify subgroup support is via the `__opencl_c_subgroups` feature macro.  Since feature macros were introduced in OpenCL C 3.0, this implies support for OpenCL C 3.0 as well.

2. Device enqueue must be supported.  Support for device enqueue can be expressed in one of two ways: either by compiling OpenCL C 2.0, or via the `__opencl_c_device_enqueue` feature macro.

After typing this out though, I suppose the line about `OpenCL C 2.0` is unnecessary, since case (1) requires OpenCL C 3.0 to express the `__opencl_c_subgroups` feature macro?

Does this issue really need the big red "OpenCL 3 Must Fix" label?

**Comment by AnastasiaStulova** [comment]
> Does this issue really need the big red "OpenCL 3 Must Fix" label?

Maybe not? Perhaps we should discuss how should issues be labeled? All I need is to make sure we address them in a timely manner.

**Comment by bashbaug** [comment]
The fix for the asciidoctor formatting is already merged.

I created PR #359 which removes the "OpenCL C 2.0" statement.  Please take a look - I think it will fix the rest of this issue.  Thanks!
