### ISSUE TITLE
Which devices are associated to a program object through clCreateProgramWithIL?

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/OpenCL-Docs#4]
Looking at the OpenCL 2.1 specification (as well as the OpenCL 1.2 Extensions specification) about `clCreateProgramWithIL()`, it does not mention which devices are associated to the resulting program object. This will be a problem when `clCompileProgram()` is called without any specified devices, as it is supposed to fallback to “all devices associated with *program*”, which would be none in that case. Unless it is expected that the compilation will not transform the IL in a device-specific way, in which case there would indeed be no need to specify devices.
If it is supposed to associate devices to the program object, I assume it would have the same behaviour as `clCreateProgramWithSource()`, for which “the devices associated with the program object are the devices associated with *context*”.

**Comment by bashbaug** [comment]
Yes, this does appear to be an oversight.  I believe the intent is for `clCreateProgramWithIL` to behave similarly to `clCreateProgramWithSource`, in which case the description of the function should include the same sentence: "The devices associated with the program object are the devices associated with _context_."  I'll ensure that this issue gets on the working group agenda.

Semi-related aside: The text for **CL_PROGRAM_DEVICES** should also be updated to describe behavior for a program created using `clCreateProgramWithBuiltinKernels`.

**Comment by bashbaug** [comment]
Thank you for raising this issue.  We discussed it in the OpenCL working group and agreed that the intent is for `clCreateProgramWithIL` to behave similarly to `clCreateProgramWithSource`, so the function description should contain the same sentence stating that "the devices associated with the program object are the devices associated with "context".

We're modifying and updating our specification toolchain slightly, so it's likely easiest if we incorporate the fix for this issue into these changes. Does that work for you? If so, no action required, otherwise feel free to open a pull request with a proposed fix.  Thanks again!

**Comment by pierremoreau** [comment]
Thank you for the quick reply and for bringing that up to the OpenCL working group. If you are going to fix the OpenCL 1.2 and 2.0 Extension specifications, as well as OpenCL 2.1 and 2.2 specifications, as part of your toolchain update, then it’s all fine by me. :-)

**Comment by bashbaug** [comment]
The OpenCL 1.2 and 2.0 extension specs and the OpenCL 2.1 API spec were updated with this change as part of https://github.com/KhronosGroup/OpenCL-Registry/pull/39.

Feel free to leave this issue open since we do still need to update the OpenCL 2.2 API spec, but I did want to let you know there has been progress.  Thanks!

**Comment by pierremoreau** [comment]
Great, thanks!
Sounds like a good idea to keep it open until OpenCL 2.2 API spec is updated as well.

**Comment by pierremoreau** [comment]
Has there been any progress regarding updating the OpenCL 2.2 API spec?

**Comment by pierremoreau** [comment]
Thank you for addressing this issue in the latest OpenCL 2.2 rev.8 API Specification.
