### ISSUE TITLE
Clarification requested on handling of clGetKernelSubGroupInfo parameter CL_KERNEL_COMPILE_NUM_SUBGROUPS in 3.0 spec

### ISSUE THREAD

**Issue by bcalidas** [KhronosGroup/OpenCL-Docs#445]
Table 34 of the OpenCL 3.0 API spec has the following reference to CL_KERNEL_COMPILE_NUM_SUBGROUPS

CL_KERNEL_COMPILE_NUM_SUB_GROUPS
Missing before version 2.1. Also see extension cl_khr_subgroups.	ignored	size_t
Returns the number of sub-groups per work-group specified in the kernel source or IL. If the sub-group count is not specified then 0 is returned.

However we could not find the corresponding token for source or IL in the OpenCL_C spec or OpenCL_Env spec. The closest reference we could find was "cl::required_num_sub_groups" in
https://www.khronos.org/registry/OpenCL/specs/2.2/pdf/OpenCL_Cxx.pdf
Should CL_KERNEL_COMPILE_NUM_SUBGROUPS be considered optional for implementations that support OpenCL C only.

**Comment by bcalidas** [comment]
Kévin Petit (Arm Limited)
Kévin Petit (Arm Limited) @kevinpetit · 10 minutes ago

Why didn't you raise this on Github?

We've discussed this in the past, there is no attribute in OpenCL C but !120 proposes one. The SPIR-V feature is the SubgroupSize execution mode that is currently tied to DSE (spirv/SPIR-V#525). This featured appeared in SPIR-V 1.1.

In practice if you don't support SPIR-V the only thing you can do is to return 0. We could maybe add a mention of this to Appendix H.

**Comment by bcalidas** [comment]
Can we change the wording in Table 34 to - 
"Returns the number of sub-groups per work-group specified in the kernel source or IL. If the sub-group count is not specified or if the kernel source is OpenCL C, then 0 is returned."

**Comment by bashbaug** [comment]
I wonder if this this informative text should be added in two places to Appendix H:

1. If subgroups are not supported, then querying `CL_KERNEL_COMPILE_NUM_SUB_GROUPS` must return 0.

2. If SPIR-V is not supported, and more specifically if SPIR-V 1.1 or newer is not supported, then querying `CL_KERNEL_COMPILE_NUM_SUB_GROUPS` must return 0, since there is currently no representation for this attribute in OpenCL C.

I'm pretty happy with the the text in the main spec:

> If the sub-group count is not specified then 0 is returned.

If we add a specific clause about OpenCL C source then I worry we're slightly that we're just creating work for if/when we do add an OpenCL C source attribute for this functionality.  Do you feel strongly about modifying the main spec text, or are additions to the appendix sufficient?

Note: We should also add these cases to the API consistency CTS test.

**Comment by bcalidas** [comment]
Appendix H already has this note on clGetKernelSubgroupInfo - "Returns CL_INVALID_OPERATION if device does not support
Subgroups."

I believe 2. would be sufficient for this issue. Regarding the wording in the main spec, I am flexible on the language, so as to leave space for future addition.

**Comment by bashbaug** [comment]
> Appendix H already has this note on clGetKernelSubgroupInfo - "Returns CL_INVALID_OPERATION if device does not support
> Subgroups."

Ah, of course.  I was searching for `CL_KERNEL_COMPILE_NUM_SUB_GROUPS` and didn't see it.  Great, one fewer thing to worry about!

I'll get a PR out for (2) for review ASAP.

**Comment by bcalidas** [comment]
Hi Ben,

Will you be pushing a PR soon.

Thanks,
Balaji

**Comment by bashbaug** [comment]
Sorry for the delay!  The PR to clarify this is here: https://github.com/KhronosGroup/OpenCL-Docs/pull/447
