### ISSUE TITLE
Clarification needed releasing memory objects used as kernel arguments

### ISSUE THREAD

**Issue by doe300** [KhronosGroup/OpenCL-Docs#45]
In the OpenCL API specification (e.g. version 2.2) for the [function](https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_API.html#_querying_unmapping_migrating_retaining_and_releasing_memory_objects) `clReleaseMemObject`, it says that:

> After the memobj reference count becomes zero and commands queued for execution on a command-queue(s) that use memobj have finished, the memory object is deleted.

The API specification for `clSetKernelArg` [states](https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_API.html#_setting_kernel_arguments) in a note:

> A kernel object does not update the reference count for objects such as memory or sampler objects specified as argument values by clSetKernelArg. Users may not rely on a kernel object to retain objects specified as argument values to the kernel.
>
> Implementations shall not allow cl_kernel objects to hold reference counts to cl_kernel arguments, [...]

Assuming a memory object is released (host-side) while a kernel accessing it is running (device-side),  which statement has precedence?
1. Is the memory object only released after the kernel has finished? If so, how is the kernel object supposed to track the memory objects set as arguments?
2. Is the memory object released immediately? Does this mean, that releasing a memory-object while a kernel execution is currently accessing it is undefined behaviour?

**Comment by Oblomov** [comment]
A possible solution to the conundrum is that while clSetKernelArg doesn't increase the reference count of memory objects, enqueueing the kernel should. It makes sense to make the reference count changes be associated with the kernel execution rather than the parameter setting because you may be launching a kernel multiple times (even concurrently) from the same kernel object, in which case you'd want to hold references to it as long as either of the enqueued is running.

If this is indeed the case, it would be appropriate to amend both the description of clRetainMemObject and the description of clEnqueue* to mention these implicit retains and releases.

**Comment by mkinsner** [comment]
I interpret the spec as saying that three conditions must be met for a memory object to be deleted, according to the following snip:

> **OpenCL 2.2, section 5.5.1:** "After the memobj reference count becomes zero and commands queued for execution on a command-queue(s) that use memobj have finished, the memory object is deleted. If memobj is a buffer object, memobj cannot be deleted until all sub-buffer objects associated with memobj are deleted."

So:
1. Ref count must be decremented to zero, and only the following quoted operations perform a reference count increment automatically, that is observable through `clGetMemObjectInfo(..., CL_MEM_REFERENCE_COUNT, ... )`

> **OpenCL 2.2, section 5.5.1:** clCreateBuffer, clCreateSubBuffer, clCreateImage and clCreatePipe perform an implicit retain.

2. No enqueued commands (in state `CL_QUEUED`, `CL_SUBMITTED`, or `CL_RUNNING`) are using the mem object

3. No sub-buffers remain that were created from the buffer object

The second and third requirements act like implicit retains that are not reflected in `CL_MEM_REFERENCE_COUNT` queries, according to my interpretation of the spec.

> Assuming a memory object is released (host-side) while a kernel accessing it is running (device-side), which statement has precedence?

I think that the first of your proposed statements is correct, according to the first spec quote above.  But I don't think the `clSetKernelArg` API or kernel object need to track the use of mem_object in the "don't delete yet" sense.  Instead, commands enqueued to a command queue must increment some internal reference count on used memory objects, which the OpenCL implementation must use when determining whether to delete a memory object such as a buffer.  This internal reference count is not reflected in `CL_MEM_REFERENCE_COUNT` queries, because it's an implementation detail.  The implicit tracking would be part of an enqueue operation's execution.

So to follow up:
1. Does the above make sense?  Is there any disagreement?
2. Has this answered your question?
3. Are any spec clarifications required given the above description?

**Comment by doe300** [comment]
Thanks for the answers.
Yes, your interpretation of the standard makes sense, I just have a few follow ups:

Do internal reference counts need to be separated from the explicit reference counts? I couldn't find any part of the specification that mentions this or anything about implicit reference counts for that matter.

I assume freeing a buffer between setting it as kernel argument and queuing the kernel execution would still be an error on the application side and nothing an implementation can do to fix this:

    cl_kernel kernel = ...
    cl_mem buffer = ...
    clSetKernelArg(kernel, 0, sizeof(cl_mem), buffer);
    clReleaseMemObject(buffer); // completely frees the buffer
    clEnqueueTask(queue, kernel, 0, NULL, NULL); // at this point, the buffer no longer exists!

Am I also right to assume that to provide this behavior, the `clEnqueueNDRangeKernel` must start tracking its used buffer arguments immediately inside the function call itself and not when the queued task is executed? Otherwise, the same problem can arise if the buffer is freed in between the queuing of the kernel execution and the actual execution.

**Comment by mkinsner** [comment]
> Do internal reference counts need to be separated from the explicit reference counts?

The "internal reference counts" aren't part of the reference counting mechanism defined by OpenCL, and don't need to be reference counts at all.  The OpenCL implementation just needs to prevent memory object deletion while the second or third conditions from my previous post are met.  This can be implemented any way that an OpenCL implementation wants to, which may include some notion of reference counting internally, but doesn't have to.  Because this is just an implementation detail, the OpenCL spec doesn't talk about any internal reference count and I don't think it needs to.

If an implementation does use reference counting to prevent deletion while the second or third conditions from previous post are met, then I don't think the externally visible (`clGetMemObjectInfo(..., CL_MEM_REFERENCE_COUNT, ... )`) mechanism can reflect that detail.  Only the functions listed in my previous post are allowed to update the reference count in a way that a user can query/observe, at that list does not include enqueued kernels using a mem object, for example.  So if an implementation uses reference counting internally for the "enqueued operation is using mem object" case, for example, then the reference count would need to be separate from the user visible reference count defined by OpenCL (at least from the user visibility perspective).

> I assume freeing a buffer between setting it as kernel argument and queuing the kernel execution would still be an error on the application side

Yes, I agree.

> Am I also right to assume that to provide this behavior, the `clEnqueueNDRangeKernel` must start tracking its used buffer arguments immediately inside the function call itself and not when the queued task is executed? 

Yes, I agree.  The spec talks about enqueued commands that have not completed.  The "do not delete" aspect comes into effect as part of the enqueuing, and not later when the enqueued command begins execution.

**Comment by doe300** [comment]
Thanks for all your feedback and clarifications.
