### ISSUE TITLE
Unclear requirements for NULL region/offset/origin arguments in various functions

### ISSUE THREAD

**Issue by karolherbst** [KhronosGroup/OpenCL-Docs#478]
There are a couple of functions which have `region`, `offset` and `origin` array arguments, but never specify if those can be NULL or not. For `region` it would make sense to return `CL_INVALID_VALUE` if it is `NULL`, but for the others the runtime could assume `0` for all elements.

List of function affected:
* clEnqueueReadBufferRect
* clEnqueueWriteBufferRect
* clEnqueueCopyBufferRect
* clEnqueueReadImage
* clEnqueueWriteImage
* clEnqueueFillImage
* clEnqueueCopyImage
* clEnqueueCopyImageToBuffer
* clEnqueueCopyBufferToImage
* clEnqueueMapImage

**Comment by bashbaug** [comment]
Thanks for reaching out!

The spec doesn't define any default behavior for a `NULL` input right now, so while I agree we _could_ assume that a `NULL` input means zero for an offset or origin, I'm not aware of any implementation that does this currently.

As you've observed, we also don't define what should happen for a `NULL` input either.  Since most implementations I've tested seem to return `CL_INVALID_VALUE` for a `NULL` input that's probably the best change to make in the short-term.  Does that sound like a reasonable resolution?

**Comment by karolherbst** [comment]
yeah, that sounds like a good idea. thanks!
