### ISSUE TITLE
Clarify the use of -cl-single-precision-constant

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#578]
The wording of `-cl-single-precision-constant` is 
> Treat double precision floating-point constant as single precision constant.

There appear to be the following interpretations:
- By default, all double literals are in double precision even if the doubles are unsupported. The implication is that in order to successfully compile the kernels using double literals on all architecture the compiler should be working around the fact that the doubles are not supported (unclear how?) or otherwise the flag has to be passed explicitly. Considering that the double precision has not been a core feature of earlier standards this implies that by default the flag has to be added in many cases.
- The flag would instruct the compiler that double literals will be converted to single-precision even if doubles are supported by the targets.

Note that upstream Clang originally converted double literals into single precision on the target that didn't support the doubles. It is not clear whether this was considered more helpful or whether there was no viable alternative to handle double literals in absence of the double support. However, there was never any functionality implemented for `-cl-single-precision-constant`.

**Comment by bashbaug** [comment]
To make this question a bit more concrete, I think the question is essentially: what happens for this kernel if the implementation doesn't support doubles?

```c
kernel void test(global float* dst)
{
    dst[0] = 0.0;
    dst[1] = cos(0.0);
}
```

Link: https://godbolt.org/z/xbxhva

Options are:

1. Compile fails, the implementation doesn't support doubles and `0.0` is a double-precision literal.
2. Compile succceeds, but a diagnostic is emitted to tell the kernel author that the double-precision `0.0` was converted to the single-precision `0.0f`.
3. Compile succceeds with no diagnostic.

It looks like Clang is currently doing (2) by default, and (3) with the `-cl-single-precision-constant` build option, which honestly seems pretty ideal.

If this is causing implementation difficulties, I think it'd be fine for (3) to be the default behavior, though it isn't quite as helpful.  I don't think (1) is a reasonable default, even if it's arguably the right thing to do, since it'd cause too much code in the wild to break.

**Comment by AnastasiaStulova** [comment]
Thanks for the analysis. There is one more aspect I would like to clarify/confirm. Clang currently generates single precision constants  even if doubles are supported in case `-cl-single-precision-constant` flag is passed.

https://godbolt.org/z/Pnq8xM

Is this expected/reasonable behavior?

**Comment by jlewis-austin** [comment]
Also want to confirm that nothing in the spec is meant to preclude a compiler from fully supporting double precision literals (via constant folding) for a single-precision target.

**Comment by AnastasiaStulova** [comment]
OpenCL WG telco summary:

-  Option (1) from (https://github.com/KhronosGroup/OpenCL-Docs/issues/578#issuecomment-796205279) is not viable due to backward compatibility. Option (2) seems like a good approach but (3) could be ok too if there is any interest.

- @jlewis-austin is suggesting another alternative where the constants would be kept in double precision even if target doesn't support doubles. Then expressions with constants would be evaluated at compile time in double precision. This would be very similar to `constexpr` in C++. In C there is no such feature so some more feasibility study is needed to understand the approach i.e. what expressions are expected to fold, or when do we cast to single precision to guarantee no double precision behavior is exposed at runtime, what happens if the evaluation result doesn't fit into signle precision, etc. The implementation feasibility should be assessed too.

**Comment by jlewis-austin** [comment]
@AnastasiaStulova a slight clarification: I wasn't proposing requiring this behavior, but rather not precluding it (ie, if a compiler doesn't want to implement it in can fall back to option (2) or whatever behavior we land on). The assumption I'm operating under is that the C/C++ specs don't address issues like this related to unsupported types.

**Comment by b-sumner** [comment]
I'd say LLVM diverged from the published spec, and the unfortunate consequence is that now we are forced to accept option (2) to maintain backward compatibility.  I think there should be a spec update since this is diverging from C and the spec defers to the C standard unless otherwise noted.

@AnastasiaStulova in my opinion the only reasonable behavior for -cl-single-precision-constant is force unsuffixed literals to single precision, regardless of whether the device supports double.

**Comment by AnastasiaStulova** [comment]
> @AnastasiaStulova a slight clarification: I wasn't proposing requiring this behavior, but rather not precluding it (ie, if a compiler doesn't want to implement it in can fall back to option (2) or whatever behavior we land on). The assumption I'm operating under is that the C/C++ specs don't address issues like this related to unsupported types.

Ok, I think it would be more like in addition to (2) since casting to single precision is unavoidable in general cases. Consider the following statement:

`float v = 1.1 * 1.2;`

The conversion and the double literal expression evaluation are already covered by C99 rules though.

However it would be interesting to see what should be the expected output of something like:

`printf("%f", 1.1 * 1.2);`

Should this print double to single precision value?

**Comment by AnastasiaStulova** [comment]
>  if an extra flag is not passed. If double type is not available there are only very minor cases that add conversions in addition to what is already in C99. The only use case I can think of is the use of double literal in printf. 

Another example is

if (1.0 > 2.0 * 3.0) ...;

However this is perhaps less practical than `printf`.

**Comment by AnastasiaStulova** [comment]
Further looking at the implementation I can't see anything strictly violating the spec wording. Clang parses the double literal as double literals but then adds implicitly casts to float in addition to the implicit casts already allowed by C99. Spec doesn't seem to say what should happen to the double literals if doubles are unsupported. So either rejecting the code or accepting with an implicit cast and a warning seem reasonable to me.

What we could have done differently if `-cl-single-precision-constant` is passed is to parse the literal as floating point literal i.e. with `f` suffix added implicitly to the end. However I am not sure whether we would get any practical difference other than a diagnostic text in slightly different form.

**Comment by AnastasiaStulova** [comment]
Anyhow considering the current situation it seems the best we can do is to add a wording to OpenCL C:

`
The implementations are allowed to implicitly cast double precistion floating point literals to signle precision. The use of double presition literal should however result in a diagnostic.`

This should accomodate cases where constant evauation is performed in double precision and where the compilation succeeds with a warning or fails with an error. However this means that `printf` with the same literals can result in different format, and it also means the diagnostic will occur even if the use of literals is fully eliminated at compile time e.g. with expressions like `(1.0 > 2.0 * 3.0)`.

I would also suggest to change the wording in `-cl-single-precision-constant` if possible to something like
`
the double literal are implicitly cast to signle precision.`

**Comment by b-sumner** [comment]
Double precision support is a core optional feature, not an extension.  So from my perspective, a programmer writing

float pimul(float x) { return x * 3.141592653589; }

should expect that this will produce 2 conversions and a double precision multiply.  This is exactly what C & C++ will do.  They should only get a single precision multiply if they explicitly use the OpenCL specific -cl-single-precision-constant, regardless of whether the platform supports double precision or not.

But since that boat has unfortunately sailed, I am not opposed to changes along the lines of what is proposed above.

**Comment by AnastasiaStulova** [comment]
> Double precision support is a core optional feature, not an extension. So from my perspective, a programmer writing
> 
> float pimul(float x) { return x * 3.141592653589; }
> 
> should expect that this will produce 2 conversions and a double precision multiply. This is exactly what C & C++ will do. They should only get a single precision multiply if they explicitly use the OpenCL specific -cl-single-precision-constant, regardless of whether the platform supports double precision or not.
> 
> But since that boat has unfortunately sailed, I am not opposed to changes along the lines of what is proposed above.

Btw just to clarify this example is compiled the same way in C99 and OpenCL C when double precision is supported. There is no deviation from C99 here at all.

The question is what do you expect to happen with this code when double precision is not supported? I don't see how can C99 regulate this situation since double precision is always supported there. Then what in the spec regulates this behavior?

**Comment by jlewis-austin** [comment]
> Ok, I think it would be more like in addition to (2) since casting to single precision is unavoidable in general cases. Consider the following statement:
> 
> `float v = 1.1 * 1.2;`

I think I agree with everything above, though I might be missing some nuances. Just to elaborate for this case where the literals are not exactly representable, the proposed wording
>The implementations are allowed to implicitly cast double-precision floating-point literals to single precision.

 would govern the following behaviors:

1. `float v = 1.1f * 1.2f;` allowed, with diagnostic 
2. `float v = (float)(1.1 * 1.2);` allowed, matches C99 behavior (my constant folding situation)
3. `float v = (float)1.1 * (float)1.2;` allowed, with diagnostic This is very near to #1, but with potential double rounding on each literal (once on parsing to double precision, and again on casting to float). 

The proposed wording seems to describe case 3, but the current `-cl-single-precision-constant` description sounds more like case 1:
`Treat double precision floating-point constant as single precision constant.`

I'd recommend using language similar to `-cl-single-precision-constant` in order to exclude case 3 unless you think that it's too pathological to worry about.

**Comment by AnastasiaStulova** [comment]
I think the current wording should cover all three cases:

1. `The use of double precision literal should however result in a diagnostic.`
2. Aligned with the full wording since it allows to cast to float but doesn't forbid the evaluation in double precision. Btw here we will have a diagnostic too since doubles are not supported but the value is convertible to float.
3. Aligned with the full wording since it allowed to cast to float. Similar to 2 the same diagnostic occurs.

Note that if `-cl-single-precision-constant` is passed then the only difference in 1-3 is that there will be no diagnostic.

> I'd recommend using language similar to -cl-single-precision-constant in order to exclude case 3 unless you think that it's too pathological to worry about.

What specifically would you suggest to keep from the old wording? Feel free to propose modifications.

FYI I would prefer if we keep the description as specific to the C99 language terminology as possible.

For example I read the wording as one of the two possibilities:
1. Parsing double literals as single literals
2. Parsing double literals regularly and then implicitly converting to single precision.

Clang for example implements 2 and it seems pretty safe as the conversion to float is well defined by C99. I have no idea what would mean parsing double as float. We could say that we append suffic to it but I am not sure how it will work with values outside of range. 

Anyway I find it more useful if we are as specific as possible - saying that `double literals are accepted and implicitly converted to float` is very specific and fully defined too because it uses C99 terminology. This way we can avoid incorrect implementations and incorrect expectations from the developers.

**Comment by jlewis-austin** [comment]
OK thanks, I didn't realize clang implements your possibility 2). The current wording (and name) of `-cl-single-precision-constant` suggests 1) though, so to me this clarification would be breaking if it now excludes 1). Is that what you're proposing? 
  
> I have no idea what would mean parsing double as float.

I'm not sure what you mean by this, are you referring to 1) not being allowed? There is no notion of a "double" string that I'm aware of (unless we start talking about hex formats)--the parser should handle any input values for either type, converting out of range values to Inf, and rounding excess precision in an implementation-defined default rounding mode.

For reference, this site illustrates differences between the two implementations: https://www.exploringbinary.com/double-rounding-errors-in-floating-point-conversions/. Out of the two, 1) is more numerically correct, so I don't think it should be specifically excluded.

**Comment by AnastasiaStulova** [comment]
> I'm not sure what you mean by this, are you referring to 1) not being allowed? There is no notion of a "double" string that I'm aware of (unless we start talking about hex formats)--the parser should handle any input values for either type, converting out of range values to Inf, and rounding excess precision in an implementation-defined default rounding mode.

Sorry I was imprecise I mean I don't know how would we parse double literals as float literals. This would mean changing the grammar of C99 language somehow?

Anyway I guess the bottom line is if there is no other way to implement this:

`Treat double precision floating-point constant as single precision constant.`

then would it not be better to be explicit and say something like:

`Implicitly convert double precision floating-point constant to single precision constant.`

I would also change `constant` to `literal` since it is more precise term in C99...

**Comment by bashbaug** [comment]
> it seems that the extension pragma also affects the implicit conversions of doubles into single-precision even on targets that support doubles but it only happens for versions up to 1.1. I am guessing this is because it was not a core functionality before?

Yes, and I think the behavior in Clang makes sense: before OpenCL C 1.2, double were only available as an extension, therefore without any extension pragma we're in the "does not support doubles" case by default.

**Comment by AnastasiaStulova** [comment]
> > it seems that the extension pragma also affects the implicit conversions of doubles into single-precision even on targets that support doubles but it only happens for versions up to 1.1. I am guessing this is because it was not a core functionality before?
> 
> Yes, and I think the behavior in Clang makes sense: before OpenCL C 1.2, doubles were only available as an extension, therefore without any extension pragma we're in the "does not support doubles" case by default.

**Comment by alycm** [comment]
> Sorry I was imprecise I mean I don't know how would we parse double literals as float literals. This would mean changing the grammar of C99 language somehow?

It's not immediately obvious to me that "Parse double precision literals as single precision literals" and "Implicitly convert all double precision literals to single precision constants" would ever result in a different answer.  Anything that is precisely representable as a single precision literal is a precise double precision constant, and anything adjacent to that may be more exactly represented as a double precision constant but should round to the same single precision value?   Perhaps that breaks at boundary conditions though.

> `Implicitly convert double precision floating-point constant to single precision constant.`
>
> I would also change `constant` to `literal` since it is more precise term in C99..

Yes, that seems more precise.

For devices that do not support doubles I agree that Clang's current behaviour seems a good compromise.  Mildly uneasy about the specification saying that a warning should be issued for that case, I think it would be only required if we explicitly state that the conversion happens.

**Comment by jlewis-austin** [comment]
> It's not immediately obvious to me that "Parse double precision literals as single precision literals" and "Implicitly convert all double precision literals to single precision constants" would ever result in a different answer. Anything that is precisely representable as a single precision literal is a precise double precision constant, and anything adjacent to that may be more exactly represented as a double precision constant but should round to the same single precision value? Perhaps that breaks at boundary conditions though.

@alycm Yes it breaks due to double rounding involving "exactly half" rounding conditions. The link I mentioned above demonstrates a few of these situations (https://www.exploringbinary.com/double-rounding-errors-in-floating-point-conversions/). While this requires carefully constructed bit patterns to demonstrate, there are a large number of them occurring throughout the floating-point range.
The difference is subtle, but from a terminology perspective, one method is referred to as "correctly rounded" and the other is not. If for the sake of standardization, we want to precisely specify one technique over the other that's fine, but it should be a conscious decision if we choose to disallow the correctly rounded implementation.
