### ISSUE TITLE
flush-to-zero behavior in case of cl-fast-relaxed-math 

### ISSUE THREAD

**Issue by nikhiljnv** [KhronosGroup/OpenCL-Docs#579]
It is unclear from the spec if cl-fast-relaxed-math allows flush-to-zero as one of the optimizations, especially if device supports CL_FP_DENORM.

**Comment by nikhiljnv** [comment]
Summarizing some of the spec areas that need attention -

1. https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#inf-nan-and-denormalized-numbers which states that Denorms may be flushed to zero without mention of cl-denorms-are-zero or CL_FP_DENORM. --> This implicitly assumes cl-denorems-are-zero is set or CL_FP_DENORM is not defined. May be we should explicitly call out when denorms can be flushed to zero and when they won't be?

2. -cl-fast-relaxed-math implies -cl-unsafe-math-optimization which states
    Allow optimizations for floating-point arithmetic that (a) assume that arguments and results are valid, (b) may violate the IEEE 754 standard, (c) assume relaxed OpenCL numerical compliance requirements as defined in the unsafe math optimization section of the OpenCL C or OpenCL SPIR-V Environment specifications, and (d) may violate edge case behavior in the OpenCL C or OpenCL SPIR-V Environment specifications. This option includes the -cl-no-signed-zeros and -cl-mad-enable options.

While -cl-no-signed-zeros and -cl-mad-enable-options are explicitly stated,  (b) may violate the IEEE 754 standard leaves wider room for any optimizations. Do we need to be more precise about what optimizations are allowed vs what is not allowed? This should partly covered by ULP error restrictions mentioned in "Table 47. ULP values for single precision built-in math functions with unsafe math optimizations in the full and embedded profiles" of https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#opencl-numerical-compliance

CTS, seems to be testing for ftz mode OFF irrespective of cl-fast-relaxed-math if CL_FP_DENORM is defined and testing with ftz on only if either CL_FP_DENORM is not defined or if cl-denorms-are-zero is passed. 
Depending on whether we consider flush-to-zero as a valid optimization in case of cl-fast-math-relaxed, we may need to update spec or CTS or both.

**Comment by alycm** [comment]
@nikhiljnv There is some history in old internal bugzilla issue 9522, particularly comments 18 and 19 which have wording for denorms.   But that wording disappears in later revisions.  There is no explanation in the ticket, call minutes around then (Feb 2013) reference discussions on fast-math but not in enough detail to cover this point.  So it is unclear if dropping the wording was a technical decision, or an arbitrary editorial change.

For the "(b) may violate the IEEE 754 standard" wording I wondered if it was just referring to the other specific changes.  However there is no explicit wording to allow things like re-association or using reciprocals in the place of divides.  I would expect unsafe-optimizations to allow those, the "may violate IEEE 754" wording is the only text to allow things like that.   But like you say, there is already a separate `-cl-denorms-are-zero` flag, `-cl-unsafe-math-optimizations` enables other flags, but not that one.

As a technicality, I would say that if we decide on allowing FTZ here it should be tied to `-cl-unsafe-math-optimization` rather than `-cl-fast-relaxed-math`.

**Comment by alycm** [comment]
Call 2021-04-06: Add that `-cl-unsafe-math-optimizations` implies `-cl-denorms-are-zero`.   `-cl-denorms-are-zero` is a hint so it doesn't break any existing implementations, arguably implementations already have the freedom to work this way due to the "may violate the IEEE 754 standard" catch-all.

There might be CTS implications, but no one has investigated that.

**Comment by alycm** [comment]
It is possible that the CTS is already compatible PR https://github.com/KhronosGroup/OpenCL-Docs/pull/597 as this is intended as clarification rather than a change.

Ways to check if the current CTS isn't compatible:
* By experimentation, on a device/implementation where `-cl-denorms-are-zero` has an effect locally add `-cl-denorms-are-zero` to tests that involve `-cl-unsafe-math-optimizations` and see if they still pass.
* By inspection, check whether the CTS can produce denormal inputs in the tests that involve `-cl-unsafe-math-optimizations`.

There is no need to extend the CTS for as the additional language represents an optional performance hint.

**Comment by alycm** [comment]
I've reopened this issue pending determining if a CTS issue is required.

**Comment by nikhiljnv** [comment]
> 
> 
> I've reopened this issue pending determining if a CTS issue is required.

Yes, we need a CTS issue. We have seen issues on NVIDIA OpenCL in case of some math functions where having ftz enabled in cl-fast-relaxed-math  were causing failures as GPU results didn't match reference calculation which are currently computed with ftz off. I can take up CTS issue and propose fixes at least for issues I am aware of.

In general, we may require CTS to test against reference calculation with ftz enabled in case of cl-fast-relaxed-math if the default computation (with ftz off) fails to match device results to match recent spec change.

**Comment by nikhiljnv** [comment]
I have filed https://github.com/KhronosGroup/OpenCL-CTS/issues/1267 to track CTS changes. May be we can close this one.

**Comment by alycm** [comment]
Yes, thank you for looking into that @nikhiljnv.  There is nothing left in the spec to do, so closing this issue.
