### ISSUE TITLE
Controlling the OpenCL C version in OpenCL >= 2.1

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/OpenCL-Docs#6]
When using the `-cl-std=CL1.2` option, the OpenCL 1.2 and 2.0 specifications say that compilation/building should fail if the device only supports OpenCL C 1.0 or 1.1:

> Calls to **clBuildProgram** or **clCompileProgram** with the *-cl-std=CL1.2* option will fail to compile the program for any devices with *CL_DEVICE_OPENCL_C_VERSION = OpenCL C 1.0* or *OpenCL C 1.1*.

However, the OpenCL 2.1 and 2.2 specifications say to only fail for *OpenCL C 1.0*:

> Calls to **clBuildProgram** or **clCompileProgram** with the *-cl-std=CL1.2* option will fail to compile the program for any devices with *CL_DEVICE_OPENCL_C_VERSION = OpenCL C 1.0*.

I guess it is more of a typo than a meant change to the behaviour in later OpenCL versions.

**Comment by pierremoreau** [comment]
Thank you for addressing this issue in the latest OpenCL 2.2 rev. 8 Specification.

Are there any plans on updating the OpenCL 2.1 Specification as well?


By the way, kudos on the new Spec format! I have only browsed a little bit in it but I really like it and it feels easier to read it! One missing feature would be to have links in the documentation: for example click on `clFinish` on page 32 and be brought to the page containing the documentation for that function, or on the ToC.

**Comment by bashbaug** [comment]
Thank you for reporting the issue, and happy to hear you like the new spec format!

The pre-2.2 specifications use a different toolchain, so updating them is a manual process unfortunately.  We're looking at ways to improve this moving forward, especially since many devices are still supporting older OpenCL versions.

Would you mind filing a separate issue for the document links?  This sounds doable and I want to be sure it doesn't slip through the cracks.  Thanks!

**Comment by pierremoreau** [comment]
Finally opened a separate issue for adding the links :slightly_smiling_face: 

Any updates on updating the OpenCL 2.1 specification?

**Comment by pierremoreau** [comment]
This seems to be tracked as part of #186 now, so closing.
