### ISSUE TITLE
Semaphores from External Handles Only

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#720]
Creating a dedicated issue for this task from #696:

We need to clarify the sentence "clCreateSemaphoreWithPropertiesKHR may return NULL value on some implementations if sema_props does an external semaphore handle type to import." When can this occur? How would an application know this could happen?

Possible resolutions are:

* This sentence is old and no longer applicable and should be removed.
* We need a mechanism to say that semaphores cannot be created in OpenCL and must be created from an external handle.

**Comment by bcalidas** [comment]
This could be related to implementations wanting to support cl_khr_external_semaphore but not cl_khr_semaphore. 
It also brings up a related question. If an implementation supports only cl_khr_semaphore, how does an application create a semaphore that is not exportable.

**Comment by bcalidas** [comment]
"clCreateSemaphoreWithPropertiesKHR may return a NULL value on some implementations if sema_props does not contain an external semaphore handle type to import. " -  This sentence should be removed since an implementation supporting cl_khr_external_semaphore must also support cl_khr_semaphore. The behavior of clCreateSemaphoreWithPropertiesKHR when sema_props does not contain an external semaphore handle type is defined in cl_khr_semaphore.

**Comment by bashbaug** [comment]
Closing - fixed by #976.
