### ISSUE TITLE
Additional Requirements Beyond C99 TC2: Wording around NaN is confusing

### ISSUE THREAD

**Issue by mantognini** [KhronosGroup/OpenCL-Docs#74]
https://github.com/KhronosGroup/OpenCL-Docs/blob/6163e510aba70daced330b7d7f54bc9b5b416252/OpenCL_C.txt#L9943-L9953

I think there are a few typos in this paragraph, specifically in the 3rd and 4th sentences. Could they simply be rewritten into:

> A *signaling* NaN shall be converted to a *non-signaling* NaN.

**Comment by bashbaug** [comment]
I did some spec archaeology to try to figure out what sentences 3 and 4 _should_ say and was surprised to find that this text has been around since OpenCL 1.0, so it doesn't appear that it's just a typo that managed to sneak in somewhere along the line.

It took me a while to figure out what this was trying to say, but I think it's something like the following (using [RFC 2110](https://tools.ietf.org/pdf/rfc2119.pdf) terms):

1. Functions that return a NaN with more than one NaN operand **must** return one of the NaN operands.
1. A signaling NaN **may** be converted to a non-signaling NaN.
1. A non-signaling NaN **must** only be converted to a non-signaling NaN.
1. A signaling NaN **should** be converted to a non-signaling NaN, but **must** be converted to a NaN.
1. When a NaN is converted to another NaN, the sign of the NaN and the NaN payload bits **may** become undefined.

I don't think the 3rd and 4th sentences can be simplified into...

> A _signaling_ NaN shall be converted to a _non-signaling_ NaN.

... since the only requirement is that a signaling NaN remains a NaN, not that it must be converted to a non-signaling NaN.

All that said, is condition (1) really necessary?  Is the returned NaN subject to the conversion rules (2) - (5)?  I guess it would be needed if an implementation wanted to do: `f( sNaN, qNaN ) -> sNaN`?

Note that this text was inherited by the OpenCL SPIR-V environment spec and needs to be fixed there, too.

Tagging @b-sumner since he usually has good insight into issues like these.

**Comment by b-sumner** [comment]
We have explicit (convert_*, (cast), etc.) and implicit conversions, and at least some of them are functions and it isn't clear which rules are supposed to apply to the explicit conversion functions.  I think we should make that clear.

Personally I am not a fan of the first rule (the only one currently addressing the behavior of built-in functions).   I see little value in imposing this burden on implementations.  Can we replace must with should?

**Comment by bashbaug** [comment]
> Personally I am not a fan of the first rule (the only one currently addressing the behavior of built-in functions). I see little value in imposing this burden on implementations. Can we replace must with should?

If I'm reading the right C99 spec section, it already has this behavior described as a "recommended practice".  From section F.9 - Mathematics:

> If a function with one or more NaN arguments returns a NaN result, the result should be
the same as one of the NaN arguments (after possible type conversion), except perhaps
for the sign.

Is this correct?  If so, and we're OK with a recommendation rather than a requirement, can this rule be removed from the OpenCL specs entirely?

**Comment by b-sumner** [comment]
Exactly.  OpenCL deliberately strayed from C99 (or later) imposing additional burden on implementations for questionable benefit.  I'd be happy to see that removed.

**Comment by bashbaug** [comment]
I took a quick look through the CTS tests and it doesn't appear that we are testing for this case.  For example:

https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_common/harness/errorHelpers.c#L432

```c
        if( isnan( reference ) && isnan( test ) )
            return 0.0f;    // if we are expecting a NaN, any NaN is fine
```

If we relax this requirement we won't cause any shipping implementations to break or become non-conformant to the spec.

Let's discuss more in next week's teleconference.

**Comment by Kerilk** [comment]
During the weekly phone I looked at the IEEE 754-2019 standard and p 49 reads:

> If two or more inputs are NaN, then the payload of the resulting NaN should be identical to the payload of one of the input NaNs if representable in the destination format. This standard does not specify which of the input NaNs will provide the payload.

I am unsure if this changes anything to the discussion though. I see the reasoning behind the standard (tracing the source of the nan) but I don't know if anybody relies on this. I am not a numerical scientist.

Brice

**Comment by alycm** [comment]
I merged https://github.com/KhronosGroup/OpenCL-Docs/pull/128 so I believe that this ticket can close.
