### ISSUE TITLE
Is it possible to overload operator in opencl kernels?

### ISSUE THREAD

**Issue by FdyCN** [KhronosGroup/OpenCL-Docs#744]
Hi guys, i have a question:  Can we overload operators in opencl kenrels? like CUDA:
```
__device__ __inline__ float4 operator -(const float4 &a, const float4 &b) {
    return make_float4(a.x - b.x, a.y - b.y, a.z - b.z, a.w - b.w);
 }

```
is it possible???

**Comment by bashbaug** [comment]
I've transferred this issue to OpenCL-Docs since it generally sees more spec questions like these than OpenCL-Headers.

It's not possible to overload operators in OpenCL C because it is C-based.

You can do this with "C++ for OpenCL" though because it is C++-based.  See: https://godbolt.org/z/MEoPKrrY5

**Comment by Oblomov** [comment]
On the upside, at least for native vector types the language already defines math operators and functions, so there's no need for it.

**Comment by MathiasMagnus** [comment]
This issue has not seen traffic for a long time and the answers should suffice. In case something remains unclear, it can always be reopened.
