### ISSUE TITLE
Clarification for "clLinkProgram" with "-cl-unsafe-math-optimizations" flag

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenCL-Docs#794]
In [compiler options](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#compiler-options): `-cl-unsafe-math-optimizations` flag is said to enable flags `-cl-no-signed-zeros`, `-cl-mad-enable`, and `-cl-denorms-are-zero`.
Then in [linker options](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#linker-options): `-cl-unsafe-math-optimizations` is said to work like corresponding compiler option.

But the `-cl-mad-enable` is not specified in the list of allowed linker options.

Does this mean, when `-cl-unsafe-math-optimizations` is passed to [`clLinkProgram`](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clLinkProgram), it only enables `-cl-denorms-are-zero` and `-cl-no-signed-zeros` flags?
Or is it possible for `-cl-unsafe-math-optimizations` to enable the use of the `MAD` instruction for the linker?

**Comment by bashbaug** [comment]
Hi, good question!  I went back and dug up an old internal issue where this was discussed (8106 for the Khronos folks) and this is a surprisingly complex issue given the diversity of processors and compilation toolchains.  There was a lot of discussion, but I believe is this a summary of the rationale behind the set of allowed "compiler options" and "linker options":

* The "compiler options" are intended to affect how your source code is compiled into ISA or IR, analogous to compiling your program with a `-c` gcc or clang option.  These options only affect this compile, and it is possible to link together two programs that were compiled with different compiler options.

* The "linker options" are intended to cover two cases:
    * Global settings that affect the entire program.  For example, whether denorms are preserved or flushed to zero may be controlled by a global state or control register and hence apply to the entire program.
    * Which library of built-in functions gets linked to create the program executable.  For example, there may be a different libraries for fast relaxed math vs. precise math.

Because `-cl-mad-enable` will mostly likely influence whether `a * b + c` is replaced by a `mad` instruction at compile-time it should definitely be considered a "compiler option".  It's not clear what a linker would do with this option though - it's unlikely that it will control global state and it's also unlikely that a built-in function libary will be compiled just with `-cl-mad-enable` (it's much more likely to be compiled with `-cl-unsafe-math-optimizations` or `-cl-fast-relaxed-math`), so it is only included in the list of allowed compiler options.

Note that if a compilation toolchain defers most or all of the compilation to ISA or IR to the link stage it can still apply `-cl-mad-enable`, it's just that the compiler options will need to preserved and deferred as well, and the replacement by `mad` must only occur for the parts of the program where `-cl-mad-enable` was specified.

Will this work for you?  Do you have a use-case for `-cl-mad-enable` as a linker option?

**Comment by SunSerega** [comment]
> Do you have a use-case for `-cl-mad-enable` as a linker option?

No, I'm making a .Net wrap and got confused about whether it should be in the `CLProgramOptions` class (common opts for compilation and link) or in `CLProgramCompOptions` (opts for compilation).
And if it is compilation specific (which as assumed was right) - should I make the property for `-cl-unsafe-math-optimizations` virtual, since it is then a combination of different options, depending on where it is defined.

---

But to confirm how I understand you:

1. `-cl-no-signed-zeros` and `-cl-denorms-are-zero` can be used both for a local (to compiled program object) optimization and for global (to whole linked assembly) switch, depending on hardware;
2. `-cl-mad-enable` is only usable for local optimization, none of the currently existing implementations apply it when linking with `-cl-unsafe-math-optimizations`;
3. The 2. is not specified in the spec, because technically, some future implementations might be able to use `MAD` or something equivalent when linking, but only as an inseparable optimization from the rest of what `-cl-unsafe-math-optimizations` does.

**Comment by bashbaug** [comment]
Hi @SunSerega, your summary above looks correct 👍 .

Please let us know if anything is still unclear or if this issue can be closed - thanks!
