### ISSUE TITLE
Interaction between Command Buffers and clSetKernelArg

### ISSUE THREAD

**Issue by FreddieWitherden** [KhronosGroup/OpenCL-Docs#799]
Reading through the command buffer extension specification it is not 100% clear how kernels which are added to command buffers interact with clSetKernelArg.  For example, if one records a kernel into a command buffer and then changes a parameter of the kernel (i) before the command buffer is enqueued and (ii) while the command buffer is pending execution?

There are some references to `cl_khr_mutable_dispatch` but it is not clear what role this plays.

Expected outcome: Calling clSetKernelArg should not impact any current or pending executions of a command buffer, but should affect any future enqueues.  Being able to change arguments of a small subset of kernels is extremely useful in HPC simulations (a classic example of a parameter that changes between runs is the simulation time `t`).

**Comment by EwanC** [comment]
Great question, kernel arguments are captured at the time `clCommandNDRangeKernelKHR` is called, and are then
immutable. Calling `clSetKernelArg` in both (i) and (ii) cases have no effect on the already recorded kernel.

However, I do think the ability to modify the configuration of recorded commands between command-buffer enqueues is valuable, and the OpenCL Working Group have ideas of a more explicit way of supporting this functionality. `cl_khr_mutable_dispatch` mentioned refers to an extension the Working Group have not released yet which enables the functionality in case (i). We are intending on releasing that provisionally soon, and this feedback will hopefully accelerate that.

In the meantime, I can add some language clarifying the interaction with `clSetKernelArg`, and also update the section on 
[interaction with other extensions](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#_interactions_with_other_extensions_2) to make it more descriptive, rather than just naming extensions which aren't public yet (since the names are in fact no longer correct).

**Comment by FreddieWitherden** [comment]
Thanks.

I also have some comments around relevant areas for future extensions and in ensuring that these are not blocked by the current design.  (Namely the embedability of command buffers inside other buffers, the ability for command buffers to support allocation and deallocation, and the freedom for command buffers to use their own queues internally.)  Is it okay if I create issues for these?

**Comment by EwanC** [comment]
Please do, those all sound like interesting directions.

**Comment by bashbaug** [comment]
Confirming: will #803 fix this issue, or is additional action required?  I don't want to link the PR and have it close this issue prematurely.  Thanks!

**Comment by bashbaug** [comment]
#803 is merged, FYI.

**Comment by EwanC** [comment]
Closing this as I think it's adequately addressed by https://github.com/KhronosGroup/OpenCL-Docs/pull/803
