### ISSUE TITLE
OpGroup{AsyncCopy,WaitEvents} execution scope

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#81]
The environement spec for says

>Scope for Execution for the **OpGroupAsyncCopy** and **OpGroupWaitEvents** instructions is
specifically limited to:
>- Workgroup

but only for OpenCL 2.1 and 2.2.

Should this not apply to all OpenCL versions?

**Comment by bashbaug** [comment]
This issue is fixed in the latest environment spec, where the following text was added to the now-unified "validation rules" chapter:

https://github.com/KhronosGroup/OpenCL-Docs/blob/master/env/validation_rules.asciidoc

> For the instructions *OpGroupAsyncCopy* and *OpGroupWaitEvents*,
_Scope_ for _Execution_ must be:
>
>  * *Workgroup*

Feel free to reopen this issue if you believe additional clarification is needed - thanks!
