### ISSUE TITLE
3 component coords for 3D image writes

### ISSUE THREAD

**Issue by biggysmith** [KhronosGroup/OpenCL-Docs#841]
Hi,

I've been having issues with undefined references to spirv functions when trying to compile with newer intel driver versions

see the discussion here:
https://community.intel.com/t5/GPU-Compute-Software/OpenCL-compiler-backend-issue-with-Drivers-gt-30-0-101-1069/m-p/1413918

Its been suggested that I ask here:  Are 4 component coords required for 3d writes, or should 3 component coords suffice?

**Comment by bashbaug** [comment]
As background, the kernel mentioned in the forum post is an OpenCL 2.2 C++ kernel language kernel.  In the OpenCL 2.2 C++ kernel language, 3D images are read from and written to using 3D coordinates:

Forum post kernel:

```c++
#include <opencl_memory>
#include <opencl_work_item>
#include <opencl_image>
#include <opencl_integer>

using namespace cl;

kernel void driver_test(
    image3d<float4, image_access::write> dst_vol
) {
    const int3 dst_coords(get_global_id(0), get_global_id(1), get_global_id(2));

    float4 source_sample(0.0f,0.0f,0.0f,0.0f);
    dst_vol.write(dst_coords, source_sample);  
}
```

Relevant part of the C++ kernel language spec:

https://registry.khronos.org/OpenCL/specs/2.2/html/OpenCL_Cxx.html#image-class

Note:

```c++
static constexpr size_t image_size = dimension_num + (Array? 1: 0);
```

This is getting carried through to SPIR-V as-is, so it remains a three-component coordinate.  This is in contrast to the same read and write operations in OpenCL C, where the 3D image read and write functions accept fourr-component coordinates.

https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#built-in-image-write-functions

e.g.

```c
void write_imagef(aQual image3d_t image, int4 coord, float4 color);
void write_imagei(aQual image3d_t image, int4 coord, int4 color);
void write_imageui(aQual image3d_t image, int4 coord, uint4 color);
```

The SPIR-V specification just says e.g. for **OpImageWrite**:

https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpImageWrite

> Coordinate is an integer scalar or vector containing non-normalized texel coordinates (u[, v] …​ [, array layer]) as needed by the definition of Image.

There is some room for interpretation for what "as needed by the definition of image" means though.

There is also no guidance given in the OpenCL SPIR-V environment spec (or the Vulkan SPIR-V environment spec, for that matter).

Some of the things we need to decide are:

* What are the expectations for SPIR-V consumers for image reads and writes using 3D images?  Presumably 4D coordinates are supported, because this is what is generated today for OpenCL C kernels.  What about 3D coordinates?  What about wider coordinates, e.g. eight-component or 16-component vectors?
* Whatever we decide, is the SPIR-V environment spec the right place to document this (probably), or should it be documented somewhere else?
* If only 4D coordinates are valid, what do we want to do for kernels written coming from the C++ kernel langauge?  Should we update or change the C++ kernel language spec (probably too late)?  Can we fix this up by adding a fourth coordinate in the SPIR-V LLVM Translator?
* Do we need to add any coverage to the CTS tests or SPIR-V LLVM Translator lit tests?

**Comment by biggysmith** [comment]
My second response on the original post also tried an OpenCL C kernel with write_imagei, which doesn't have an  image2d_t, int4 overload that I can see.  It produces an undefined reference error: __builtin_spirv_OpImageWrite_img2d_wo_v2i32_v4i32_i32.

So I'm guessing this issue extends beyond just the 3D case, and C++ case.

**Comment by bashbaug** [comment]
> My second response on the original post also tried an OpenCL C kernel with a 2D write_imagei, which doesn't have an image2d_t, int4 overload that I can see. It produces an undefined reference error: __builtin_spirv_OpImageWrite_img2d_wo_v2i32_v4i32_i32.

I think this is a slightly different issue and is related to the optional **SignExtend** and **ZeroExtend** image operands that were added in SPIR-V 1.4:

https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Image_Operands

By default, the SPIR-V LLVM Translator appears to be generating SPIR-V 1.4 with these optional image operands, but we don't yet accept SPIR-V 1.4, so we aren't finding the right overload when there is an extra operand.  If I generate a lower version of SPIR-V without the optional image operand (by passing e.g. `--spirv-max-version=1.2`) then there are no optional image operands and my 2D write_imagei kernel seems to be working.  Can you give this a try?

**Comment by biggysmith** [comment]
passing --spirv-max-version=1.2 to llvm-spirv makes it work, thanks!

It took me a while to check that it worked though, as I kept getting CL_INVALID_KERNEL_NAME error from clCreateKernel. Seems a ".1" gets appended to the kernel name, so I had to pass "window_level.1".  I don't know where this ".1" comes from.

**Comment by bashbaug** [comment]
Discussed in the March 5th teleconference:

* We're going to require 4D coordinates.
* Need to check CTS test coverage.
* Need to check SPIR-V validator coverage.
