### ISSUE TITLE
Array to pointer const-correctness issues

### ISSUE THREAD

**Issue by presentfactory** [KhronosGroup/OpenCL-Docs#9]
While working with the OpenCL 2.0 API (this also seems to exist in 2.2 as well), I noticed that I could not properly pass a constant array of C-style strings to `clCreateProgramWithSource` due to its signature (and others of the same nature) being `type const **` instead of `type const * const *`. Usually this would imply that the function will modify the memory pointed to in some way, but I cannot find any reference to this being the case in the functions in question. Additionally other non-double pointer parameters on the same functions seem to be const-correct such as the `lengths` parameter on `clCreateProgramWithSource`, so this seems to just be an oversight in these cases. A list of the functions which seem to do this are as follows (pretty much every reference to a `**` in the OpenCL 2.2 Specification, there may be more that the find did not reveal properly):

- `clEnqueueSVMMigrateMem` (Not sure about this one because I have never used it)
- `clCreateProgramWithSource`
- `clCreateProgramWithBinary`
- `clCompileProgram`
- `clEnqueueNativeKernel` (Again not sure due to not having used it, seems to imply something is replaced)

An example of how this causes issues is shown below, the "good" function signature works with both const and non-const arrays while the "bad" signature will fail with the const array:

```c++
#include <array>

// void foo(char const **) {} // Bad
void foo(char const * const *) {} // Good

int main() {
  std::array<char const *, 1U> const a{ "a" };
  std::array<char const *, 1U> b{ "b" };
  
  foo(a.data());
  foo(b.data());
}
```

Unless these functions do need to actually modify the memory being passed to them, I do not see why they should remain this way, unless they really do need it for some bizarre reason (or perhaps I read the API incorrectly), in which case I'd like to understand why. Thanks.

**Comment by bashbaug** [comment]
Interesting, thanks for the report and the example.  We'll discuss this in our working group meeting and get back to you.

**Comment by bashbaug** [comment]
Hi, thanks again for reporting the issue and apologies for the very slow reply.

We've been discussing this issue in the working group and while we agree that this is likely a bug (going all the way back to OpenCL 1.0!), our concern is that fixing this issue as a bugfix may cause compatibility issues:  Specifically, if we fixed this issue and changed the headers, old code would continue to build and run correctly with the new headers, but new code would fail to build with old headers.

Due to the possible compatibility issues we'd like to fix this in our next version of OpenCL.  Would this work for you?  Thanks!

**Comment by presentfactory** [comment]
Yes that works fine. Thanks for addressing it!

**Comment by bashbaug** [comment]
Great.  We're tracking this as internal issue 91 for the next version of OpenCL, so I'm going to close this issue.  Thanks again!
