### ISSUE TITLE
Clarification which devices should be returned with CL_PROGRAM_DEVICES

### ISSUE THREAD

**Issue by RABijl** [KhronosGroup/OpenCL-Docs#949]
In section [5.8.9](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_program_object_queries), table 29 it says that `CL_PROGRAM_DEVICES` can return a subset of devices created with `clCreateProgramWithBinary`.  My question is what should be returned if `clBuildProgram` was called on a subset of devices in the context for which a source has been provided?

an example scenario:

1. call `clCreateProgramWithSource` with a context with two devices for which the source applies to both.
2. call `clBuildProgram` with one device as argument.
3. call `clGetProgramInfo` to retrieve `CL_PROGRAM_DEVICES`. Should it return both devices or only the device for which the program has been built?

I'm hoping someone can help clarify the documentation on what should happen in such a scenario.

**Comment by bashbaug** [comment]
Caveat: I haven't tested this for our implementation or for any other implementations, but because the description of the return value for `CL_PROGRAM_DEVICES` is "the list of devices associated with the program object", and not something like "the list of devices for which an executable program has been built", I think I would expect the query to return both devices in your scenario above.

This also seems consistent with the queries for `CL_PROGRAM_BINARY_SIZES` and `CL_PROGRAM_BINARIES`, where the number of elements in the returned arrays is determined by "the number of devices associated with program", and where "if a binary is not available for a device(s), a size of zero is returned."

Will this work for you?
