### ISSUE TITLE
Error in OpenCL 1.2 reference pages

### ISSUE THREAD

**Issue by StrahinjaStamenkovic** [KhronosGroup/OpenCL-Docs#963]
Inside the [reference pages](https://registry.khronos.org/OpenCL/sdk/1.2/docs/man/xhtml/) for OpenCL 1.2, specifically clSetEventCallback, under the errors section, the following is stated as explanation for CL_INVALID_VALUE:

> CL_INVALID_VALUE if pfn_event_notify is NULL or if command_exec_callback_type is not CL_COMPLETE.

And if we look at the [PDF](https://registry.khronos.org/OpenCL/specs/opencl-1.2.pdf) of the OpenCL 1.2 Specification it includes CL_SUBMITTED and CL_RUNNING:

> CL_INVALID_VALUE if pfn_event_notify is NULL or if command_exec_callback_type is not CL_SUBMITTED, CL_RUNNING or CL_COMPLETE

The same [reference pages](https://registry.khronos.org/OpenCL/sdk/2.0/docs/man/xhtml/) but now for OpenCL 2.0 also include CL_SUBMITTED and CL_RUNNING:

> CL_INVALID_VALUE if pfn_event_notify is NULL or if command_exec_callback_type is not CL_SUBMITTED, CL_RUNNING or CL_COMPLETE.

So this is probably an error in the reference pages for OpenCL 1.2 and should be fixed

**Comment by bashbaug** [comment]
Hi, thanks for the bug report!

We "unified" both the OpenCL specifications and the reference pages a while back, so even though the URL path still says "3.0" the latest reference pages cover all OpenCL versions, and this issue is fixed in the latest reference pages:

https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/clSetEventCallback.html

We keep the older specifications and reference pages around for, well, reference, but they aren't actively maintained.  Will using the newer 3.0 / unified reference pages work for you?

@outofcontrol Note that the 1.2 reference page is still the top google hit when I search for `clSetEventCallback` and the 3.0/unified link isn't to be found.  The 3.0 reference page is the top duckduckgo hit so it doesn't seem to be completely hidden. 
 Is there anything we can do to fix this?

**Comment by StrahinjaStamenkovic** [comment]
Hello, sorry for the late response,

I'm currently working on a project that specifically uses (makes support for) OpenCL 1.2 version with future plans to support the 2.0 version. This is the reason why I was looking at the specification specifically for the 1.2 version since I wanted to make sure if any changes were made between the two versions for any function behavior. 

So if i understood you correctly, there are no differences in API behavior between OpenCL versions and using the reference pages you provided would work for any version?

**Comment by StrahinjaStamenkovic** [comment]
I see, thanks for the clarification. Should i close this issue?

**Comment by bashbaug** [comment]
> On the per-function page you linked, when I click "missing before", it tries to jump to the `#unified-spec` anchor, but it's missing there. Maybe it should link to a separate page?

We should fix this.  @alycm will take a look.

**Comment by outofcontrol** [comment]
> @outofcontrol Note that the 1.2 reference page is still the top google hit when I search for clSetEventCallback and the 3.0/unified link isn't to be found. The 3.0 reference page is the top duckduckgo hit so it doesn't seem to be completely hidden.

Google is refusing to give much credence to v3.0. Bing and DDG are happy with it. Google is getting more strict on load times, accessibility and mobile accessibility.

Perhaps good to open a separate issue for our Google SEO issues?

**Comment by alycm** [comment]
I've filed #968 about SEO, closing this ticket again.
