### ISSUE TITLE
broken refpage links for CL_VERSION_X_Y macros

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#981]
The refpage links for the `CL_VERSION_X_Y` macros in the "see also" sections all appear to be broken.

Example for [clCreateBuffer](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/clCreateBuffer.html#_see_also) and [CL_VERSION_1_0](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/CL_VERSION_1_0.html) (the first link works, the second doesn't).

I suspect this should redirect to [preprocessorDirectives](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/preprocessorDirectives.html) but I'm not quite sure what magic is needed to make this happen.

@oddhack might be able to help...

**Comment by oddhack** [comment]
There are no refpage blocks corresponding to these. Two options:

* Do like we did in Vulkan and create refpage blocks for each. See e.g. https://github.com/KhronosGroup/Vulkan-Docs/blob/main/appendices/versions.adoc (not in-browser, github's asciidoc renderer can't deal with our custom macros). I set this up to include autogenerated summaries of the interfaces in each API version, which should be possible with CL but would require a bit more work. If you want I can integrate that into the slowly ongoing extension markup-into-main-spec work I'm doing in background. I have to get the interface generation working anyway for the extension appendices. For the time being, we could drop the autogenerated includes and just point to the corresponding refpage / part of the spec.
* Filter out the CL_VERSION_X_Y autogenerated dependencies from the See Also list.

Making them redirect to preprocessorDirectives would require intrusive script changes, since there's no semantic connection between them in XML or spec. My recommendation is to imbed a minimal form of the refpage blocks without the generated interface includes for now, just after the preprocessorDirectives block (or perhaps in the API spec, since that's where virtually all of the See Alsos are going to come from). If you want I can take a swing at that this week.

**Comment by bashbaug** [comment]
Interesting - I was thinking there might be something happening on the server side since the links for the types like [cl_context](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/cl_context.html) somehow end up on the [abstractDataTypes](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/abstractDataTypes.html) page instead - there is no "cl_context.html" in the OpenCL-Registry repo.

If this isn't possible though - or even it if is - I think we could filter the CL_VERSION_X_Y dependencies from the "see also" list, since I'm not sure they're adding much value.

**Comment by oddhack** [comment]
Hm, try editing

> [open,refpage='preprocessorDirectives',desc='Preprocessor Directives and Macros',type='freeform',spec='clang',anchor='preprocessor-directives-and-macros',xrefs='clBuildProgram mathConstants EXTENSION FP_CONTRACT']

in OpenCL_C.txt to add the attribute

> ,alias='CL_VERSION_1_0 CL_VERSION_1_1 CL_VERSION_1_2']

at the end. This should add some HTML rewrite rules on the server that make CL_VERSION_1_x.html all resolve to that refpage (but you will not be able to see the difference locally unless you're running Apache on your workstation).

**Comment by bashbaug** [comment]
With https://github.com/KhronosGroup/OpenCL-Docs/pull/983 merged the links should work properly as soon as we build and publish updated reference pages.

We could still consider #984 and filter the version macros if we decide they are unnecessary.  Or, if we're happy keeping them, we can close this issue.
